// Code generated by thriftgo (0.4.5). DO NOT EDIT.

package model

import (
	"fmt"
)

type Constraints struct {
	City             string   `thrift:"city,1" frugal:"1,default,string" json:"city"`
	StartDate        string   `thrift:"start_date,2" frugal:"2,default,string" json:"start_date"`
	EndDate          string   `thrift:"end_date,3" frugal:"3,default,string" json:"end_date"`
	PartySize        int32    `thrift:"party_size,4" frugal:"4,default,i32" json:"party_size"`
	BudgetCents      int64    `thrift:"budget_cents,5" frugal:"5,default,i64" json:"budget_cents"`
	BudgetScope      string   `thrift:"budget_scope,6" frugal:"6,default,string" json:"budget_scope"`
	BudgetTotalCents int64    `thrift:"budget_total_cents,7" frugal:"7,default,i64" json:"budget_total_cents"`
	Interests        []string `thrift:"interests,8" frugal:"8,default,list<string>" json:"interests"`
	Pace             string   `thrift:"pace,9" frugal:"9,default,string" json:"pace"`
	Transport        string   `thrift:"transport,10" frugal:"10,default,string" json:"transport"`
}

func NewConstraints() *Constraints {
	return &Constraints{}
}

func (p *Constraints) InitDefault() {
}

func (p *Constraints) GetCity() (v string) {
	return p.City
}

func (p *Constraints) GetStartDate() (v string) {
	return p.StartDate
}

func (p *Constraints) GetEndDate() (v string) {
	return p.EndDate
}

func (p *Constraints) GetPartySize() (v int32) {
	return p.PartySize
}

func (p *Constraints) GetBudgetCents() (v int64) {
	return p.BudgetCents
}

func (p *Constraints) GetBudgetScope() (v string) {
	return p.BudgetScope
}

func (p *Constraints) GetBudgetTotalCents() (v int64) {
	return p.BudgetTotalCents
}

func (p *Constraints) GetInterests() (v []string) {
	return p.Interests
}

func (p *Constraints) GetPace() (v string) {
	return p.Pace
}

func (p *Constraints) GetTransport() (v string) {
	return p.Transport
}
func (p *Constraints) SetCity(val string) {
	p.City = val
}
func (p *Constraints) SetStartDate(val string) {
	p.StartDate = val
}
func (p *Constraints) SetEndDate(val string) {
	p.EndDate = val
}
func (p *Constraints) SetPartySize(val int32) {
	p.PartySize = val
}
func (p *Constraints) SetBudgetCents(val int64) {
	p.BudgetCents = val
}
func (p *Constraints) SetBudgetScope(val string) {
	p.BudgetScope = val
}
func (p *Constraints) SetBudgetTotalCents(val int64) {
	p.BudgetTotalCents = val
}
func (p *Constraints) SetInterests(val []string) {
	p.Interests = val
}
func (p *Constraints) SetPace(val string) {
	p.Pace = val
}
func (p *Constraints) SetTransport(val string) {
	p.Transport = val
}

func (p *Constraints) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Constraints(%+v)", *p)
}

var fieldIDToName_Constraints = map[int16]string{
	1:  "city",
	2:  "start_date",
	3:  "end_date",
	4:  "party_size",
	5:  "budget_cents",
	6:  "budget_scope",
	7:  "budget_total_cents",
	8:  "interests",
	9:  "pace",
	10: "transport",
}

type Place struct {
	Id               string   `thrift:"id,1" frugal:"1,default,string" json:"id"`
	Provider         string   `thrift:"provider,2" frugal:"2,default,string" json:"provider"`
	ProviderPoiId    string   `thrift:"provider_poi_id,3" frugal:"3,default,string" json:"provider_poi_id"`
	Name             string   `thrift:"name,4" frugal:"4,default,string" json:"name"`
	City             string   `thrift:"city,5" frugal:"5,default,string" json:"city"`
	CityCode         string   `thrift:"city_code,6" frugal:"6,default,string" json:"city_code"`
	AdCode           string   `thrift:"ad_code,7" frugal:"7,default,string" json:"ad_code"`
	Location         string   `thrift:"location,8" frugal:"8,default,string" json:"location"`
	CoordinateSystem string   `thrift:"coordinate_system,9" frugal:"9,default,string" json:"coordinate_system"`
	Address          string   `thrift:"address,10" frugal:"10,default,string" json:"address"`
	TypeCode         string   `thrift:"type_code,11" frugal:"11,default,string" json:"type_code"`
	Tags             []string `thrift:"tags,12" frugal:"12,default,list<string>" json:"tags"`
	DurationMinutes  int32    `thrift:"duration_minutes,13" frugal:"13,default,i32" json:"duration_minutes"`
	OpenMinute       *int32   `thrift:"open_minute,14,optional" frugal:"14,optional,i32" json:"open_minute,omitempty"`
	CloseMinute      *int32   `thrift:"close_minute,15,optional" frugal:"15,optional,i32" json:"close_minute,omitempty"`
	FeeCents         *int64   `thrift:"fee_cents,16,optional" frugal:"16,optional,i64" json:"fee_cents,omitempty"`
	FeeSource        string   `thrift:"fee_source,17" frugal:"17,default,string" json:"fee_source"`
	Active           bool     `thrift:"active,18" frugal:"18,default,bool" json:"active"`
	FetchedAt        string   `thrift:"fetched_at,19" frugal:"19,default,string" json:"fetched_at"`
	Version          int64    `thrift:"version,20" frugal:"20,default,i64" json:"version"`
}

func NewPlace() *Place {
	return &Place{}
}

func (p *Place) InitDefault() {
}

func (p *Place) GetId() (v string) {
	return p.Id
}

func (p *Place) GetProvider() (v string) {
	return p.Provider
}

func (p *Place) GetProviderPoiId() (v string) {
	return p.ProviderPoiId
}

func (p *Place) GetName() (v string) {
	return p.Name
}

func (p *Place) GetCity() (v string) {
	return p.City
}

func (p *Place) GetCityCode() (v string) {
	return p.CityCode
}

func (p *Place) GetAdCode() (v string) {
	return p.AdCode
}

func (p *Place) GetLocation() (v string) {
	return p.Location
}

func (p *Place) GetCoordinateSystem() (v string) {
	return p.CoordinateSystem
}

func (p *Place) GetAddress() (v string) {
	return p.Address
}

func (p *Place) GetTypeCode() (v string) {
	return p.TypeCode
}

func (p *Place) GetTags() (v []string) {
	return p.Tags
}

func (p *Place) GetDurationMinutes() (v int32) {
	return p.DurationMinutes
}

var Place_OpenMinute_DEFAULT int32

func (p *Place) GetOpenMinute() (v int32) {
	if !p.IsSetOpenMinute() {
		return Place_OpenMinute_DEFAULT
	}
	return *p.OpenMinute
}

var Place_CloseMinute_DEFAULT int32

func (p *Place) GetCloseMinute() (v int32) {
	if !p.IsSetCloseMinute() {
		return Place_CloseMinute_DEFAULT
	}
	return *p.CloseMinute
}

var Place_FeeCents_DEFAULT int64

func (p *Place) GetFeeCents() (v int64) {
	if !p.IsSetFeeCents() {
		return Place_FeeCents_DEFAULT
	}
	return *p.FeeCents
}

func (p *Place) GetFeeSource() (v string) {
	return p.FeeSource
}

func (p *Place) GetActive() (v bool) {
	return p.Active
}

func (p *Place) GetFetchedAt() (v string) {
	return p.FetchedAt
}

func (p *Place) GetVersion() (v int64) {
	return p.Version
}
func (p *Place) SetId(val string) {
	p.Id = val
}
func (p *Place) SetProvider(val string) {
	p.Provider = val
}
func (p *Place) SetProviderPoiId(val string) {
	p.ProviderPoiId = val
}
func (p *Place) SetName(val string) {
	p.Name = val
}
func (p *Place) SetCity(val string) {
	p.City = val
}
func (p *Place) SetCityCode(val string) {
	p.CityCode = val
}
func (p *Place) SetAdCode(val string) {
	p.AdCode = val
}
func (p *Place) SetLocation(val string) {
	p.Location = val
}
func (p *Place) SetCoordinateSystem(val string) {
	p.CoordinateSystem = val
}
func (p *Place) SetAddress(val string) {
	p.Address = val
}
func (p *Place) SetTypeCode(val string) {
	p.TypeCode = val
}
func (p *Place) SetTags(val []string) {
	p.Tags = val
}
func (p *Place) SetDurationMinutes(val int32) {
	p.DurationMinutes = val
}
func (p *Place) SetOpenMinute(val *int32) {
	p.OpenMinute = val
}
func (p *Place) SetCloseMinute(val *int32) {
	p.CloseMinute = val
}
func (p *Place) SetFeeCents(val *int64) {
	p.FeeCents = val
}
func (p *Place) SetFeeSource(val string) {
	p.FeeSource = val
}
func (p *Place) SetActive(val bool) {
	p.Active = val
}
func (p *Place) SetFetchedAt(val string) {
	p.FetchedAt = val
}
func (p *Place) SetVersion(val int64) {
	p.Version = val
}

func (p *Place) IsSetOpenMinute() bool {
	return p.OpenMinute != nil
}

func (p *Place) IsSetCloseMinute() bool {
	return p.CloseMinute != nil
}

func (p *Place) IsSetFeeCents() bool {
	return p.FeeCents != nil
}

func (p *Place) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Place(%+v)", *p)
}

var fieldIDToName_Place = map[int16]string{
	1:  "id",
	2:  "provider",
	3:  "provider_poi_id",
	4:  "name",
	5:  "city",
	6:  "city_code",
	7:  "ad_code",
	8:  "location",
	9:  "coordinate_system",
	10: "address",
	11: "type_code",
	12: "tags",
	13: "duration_minutes",
	14: "open_minute",
	15: "close_minute",
	16: "fee_cents",
	17: "fee_source",
	18: "active",
	19: "fetched_at",
	20: "version",
}

type Cost struct {
	Category    string `thrift:"category,1" frugal:"1,default,string" json:"category"`
	AmountCents *int64 `thrift:"amount_cents,2,optional" frugal:"2,optional,i64" json:"amount_cents,omitempty"`
	Unit        string `thrift:"unit,3" frugal:"3,default,string" json:"unit"`
	Source      string `thrift:"source,4" frugal:"4,default,string" json:"source"`
	Estimated   bool   `thrift:"estimated,5" frugal:"5,default,bool" json:"estimated"`
}

func NewCost() *Cost {
	return &Cost{}
}

func (p *Cost) InitDefault() {
}

func (p *Cost) GetCategory() (v string) {
	return p.Category
}

var Cost_AmountCents_DEFAULT int64

func (p *Cost) GetAmountCents() (v int64) {
	if !p.IsSetAmountCents() {
		return Cost_AmountCents_DEFAULT
	}
	return *p.AmountCents
}

func (p *Cost) GetUnit() (v string) {
	return p.Unit
}

func (p *Cost) GetSource() (v string) {
	return p.Source
}

func (p *Cost) GetEstimated() (v bool) {
	return p.Estimated
}
func (p *Cost) SetCategory(val string) {
	p.Category = val
}
func (p *Cost) SetAmountCents(val *int64) {
	p.AmountCents = val
}
func (p *Cost) SetUnit(val string) {
	p.Unit = val
}
func (p *Cost) SetSource(val string) {
	p.Source = val
}
func (p *Cost) SetEstimated(val bool) {
	p.Estimated = val
}

func (p *Cost) IsSetAmountCents() bool {
	return p.AmountCents != nil
}

func (p *Cost) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Cost(%+v)", *p)
}

var fieldIDToName_Cost = map[int16]string{
	1: "category",
	2: "amount_cents",
	3: "unit",
	4: "source",
	5: "estimated",
}

type Activity struct {
	Id          string  `thrift:"id,1" frugal:"1,default,string" json:"id"`
	Date        string  `thrift:"date,2" frugal:"2,default,string" json:"date"`
	StartMinute int32   `thrift:"start_minute,3" frugal:"3,default,i32" json:"start_minute"`
	EndMinute   int32   `thrift:"end_minute,4" frugal:"4,default,i32" json:"end_minute"`
	Kind        string  `thrift:"kind,5" frugal:"5,default,string" json:"kind"`
	PlaceId     string  `thrift:"place_id,6" frugal:"6,default,string" json:"place_id"`
	Title       string  `thrift:"title,7" frugal:"7,default,string" json:"title"`
	Reason      string  `thrift:"reason,8" frugal:"8,default,string" json:"reason"`
	Place       *Place  `thrift:"place,9,optional" frugal:"9,optional,Place" json:"place,omitempty"`
	Costs       []*Cost `thrift:"costs,10" frugal:"10,default,list<Cost>" json:"costs"`
}

func NewActivity() *Activity {
	return &Activity{}
}

func (p *Activity) InitDefault() {
}

func (p *Activity) GetId() (v string) {
	return p.Id
}

func (p *Activity) GetDate() (v string) {
	return p.Date
}

func (p *Activity) GetStartMinute() (v int32) {
	return p.StartMinute
}

func (p *Activity) GetEndMinute() (v int32) {
	return p.EndMinute
}

func (p *Activity) GetKind() (v string) {
	return p.Kind
}

func (p *Activity) GetPlaceId() (v string) {
	return p.PlaceId
}

func (p *Activity) GetTitle() (v string) {
	return p.Title
}

func (p *Activity) GetReason() (v string) {
	return p.Reason
}

var Activity_Place_DEFAULT *Place

func (p *Activity) GetPlace() (v *Place) {
	if !p.IsSetPlace() {
		return Activity_Place_DEFAULT
	}
	return p.Place
}

func (p *Activity) GetCosts() (v []*Cost) {
	return p.Costs
}
func (p *Activity) SetId(val string) {
	p.Id = val
}
func (p *Activity) SetDate(val string) {
	p.Date = val
}
func (p *Activity) SetStartMinute(val int32) {
	p.StartMinute = val
}
func (p *Activity) SetEndMinute(val int32) {
	p.EndMinute = val
}
func (p *Activity) SetKind(val string) {
	p.Kind = val
}
func (p *Activity) SetPlaceId(val string) {
	p.PlaceId = val
}
func (p *Activity) SetTitle(val string) {
	p.Title = val
}
func (p *Activity) SetReason(val string) {
	p.Reason = val
}
func (p *Activity) SetPlace(val *Place) {
	p.Place = val
}
func (p *Activity) SetCosts(val []*Cost) {
	p.Costs = val
}

func (p *Activity) IsSetPlace() bool {
	return p.Place != nil
}

func (p *Activity) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Activity(%+v)", *p)
}

var fieldIDToName_Activity = map[int16]string{
	1:  "id",
	2:  "date",
	3:  "start_minute",
	4:  "end_minute",
	5:  "kind",
	6:  "place_id",
	7:  "title",
	8:  "reason",
	9:  "place",
	10: "costs",
}

type Route struct {
	FromItemId   string `thrift:"from_item_id,1" frugal:"1,default,string" json:"from_item_id"`
	ToItemId     string `thrift:"to_item_id,2" frugal:"2,default,string" json:"to_item_id"`
	Date         string `thrift:"date,3" frugal:"3,default,string" json:"date"`
	Mode         string `thrift:"mode,4" frugal:"4,default,string" json:"mode"`
	DistanceM    int64  `thrift:"distance_m,5" frugal:"5,default,i64" json:"distance_m"`
	DurationS    int64  `thrift:"duration_s,6" frugal:"6,default,i64" json:"duration_s"`
	FeeCents     *int64 `thrift:"fee_cents,7,optional" frugal:"7,optional,i64" json:"fee_cents,omitempty"`
	Provider     string `thrift:"provider,8" frugal:"8,default,string" json:"provider"`
	QueriedAt    string `thrift:"queried_at,9" frugal:"9,default,string" json:"queried_at"`
	Summary      string `thrift:"summary,10" frugal:"10,default,string" json:"summary"`
	Polyline     string `thrift:"polyline,11" frugal:"11,default,string" json:"polyline"`
	FromLocation string `thrift:"from_location,12" frugal:"12,default,string" json:"from_location"`
	ToLocation   string `thrift:"to_location,13" frugal:"13,default,string" json:"to_location"`
}

func NewRoute() *Route {
	return &Route{}
}

func (p *Route) InitDefault() {
}

func (p *Route) GetFromItemId() (v string) {
	return p.FromItemId
}

func (p *Route) GetToItemId() (v string) {
	return p.ToItemId
}

func (p *Route) GetDate() (v string) {
	return p.Date
}

func (p *Route) GetMode() (v string) {
	return p.Mode
}

func (p *Route) GetDistanceM() (v int64) {
	return p.DistanceM
}

func (p *Route) GetDurationS() (v int64) {
	return p.DurationS
}

var Route_FeeCents_DEFAULT int64

func (p *Route) GetFeeCents() (v int64) {
	if !p.IsSetFeeCents() {
		return Route_FeeCents_DEFAULT
	}
	return *p.FeeCents
}

func (p *Route) GetProvider() (v string) {
	return p.Provider
}

func (p *Route) GetQueriedAt() (v string) {
	return p.QueriedAt
}

func (p *Route) GetSummary() (v string) {
	return p.Summary
}

func (p *Route) GetPolyline() (v string) {
	return p.Polyline
}

func (p *Route) GetFromLocation() (v string) {
	return p.FromLocation
}

func (p *Route) GetToLocation() (v string) {
	return p.ToLocation
}
func (p *Route) SetFromItemId(val string) {
	p.FromItemId = val
}
func (p *Route) SetToItemId(val string) {
	p.ToItemId = val
}
func (p *Route) SetDate(val string) {
	p.Date = val
}
func (p *Route) SetMode(val string) {
	p.Mode = val
}
func (p *Route) SetDistanceM(val int64) {
	p.DistanceM = val
}
func (p *Route) SetDurationS(val int64) {
	p.DurationS = val
}
func (p *Route) SetFeeCents(val *int64) {
	p.FeeCents = val
}
func (p *Route) SetProvider(val string) {
	p.Provider = val
}
func (p *Route) SetQueriedAt(val string) {
	p.QueriedAt = val
}
func (p *Route) SetSummary(val string) {
	p.Summary = val
}
func (p *Route) SetPolyline(val string) {
	p.Polyline = val
}
func (p *Route) SetFromLocation(val string) {
	p.FromLocation = val
}
func (p *Route) SetToLocation(val string) {
	p.ToLocation = val
}

func (p *Route) IsSetFeeCents() bool {
	return p.FeeCents != nil
}

func (p *Route) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Route(%+v)", *p)
}

var fieldIDToName_Route = map[int16]string{
	1:  "from_item_id",
	2:  "to_item_id",
	3:  "date",
	4:  "mode",
	5:  "distance_m",
	6:  "duration_s",
	7:  "fee_cents",
	8:  "provider",
	9:  "queried_at",
	10: "summary",
	11: "polyline",
	12: "from_location",
	13: "to_location",
}

type Plan struct {
	Title      string      `thrift:"title,1" frugal:"1,default,string" json:"title"`
	Summary    string      `thrift:"summary,2" frugal:"2,default,string" json:"summary"`
	Activities []*Activity `thrift:"activities,3" frugal:"3,default,list<Activity>" json:"activities"`
	Routes     []*Route    `thrift:"routes,4" frugal:"4,default,list<Route>" json:"routes"`
	Warnings   []string    `thrift:"warnings,5" frugal:"5,default,list<string>" json:"warnings"`
}

func NewPlan() *Plan {
	return &Plan{}
}

func (p *Plan) InitDefault() {
}

func (p *Plan) GetTitle() (v string) {
	return p.Title
}

func (p *Plan) GetSummary() (v string) {
	return p.Summary
}

func (p *Plan) GetActivities() (v []*Activity) {
	return p.Activities
}

func (p *Plan) GetRoutes() (v []*Route) {
	return p.Routes
}

func (p *Plan) GetWarnings() (v []string) {
	return p.Warnings
}
func (p *Plan) SetTitle(val string) {
	p.Title = val
}
func (p *Plan) SetSummary(val string) {
	p.Summary = val
}
func (p *Plan) SetActivities(val []*Activity) {
	p.Activities = val
}
func (p *Plan) SetRoutes(val []*Route) {
	p.Routes = val
}
func (p *Plan) SetWarnings(val []string) {
	p.Warnings = val
}

func (p *Plan) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Plan(%+v)", *p)
}

var fieldIDToName_Plan = map[int16]string{
	1: "title",
	2: "summary",
	3: "activities",
	4: "routes",
	5: "warnings",
}

type Scope struct {
	Date            string   `thrift:"date,1" frugal:"1,default,string" json:"date"`
	StartMinute     int32    `thrift:"start_minute,2" frugal:"2,default,i32" json:"start_minute"`
	EndMinute       int32    `thrift:"end_minute,3" frugal:"3,default,i32" json:"end_minute"`
	EditableItemIds []string `thrift:"editable_item_ids,4" frugal:"4,default,list<string>" json:"editable_item_ids"`
	LockedItemIds   []string `thrift:"locked_item_ids,5" frugal:"5,default,list<string>" json:"locked_item_ids"`
}

func NewScope() *Scope {
	return &Scope{}
}

func (p *Scope) InitDefault() {
}

func (p *Scope) GetDate() (v string) {
	return p.Date
}

func (p *Scope) GetStartMinute() (v int32) {
	return p.StartMinute
}

func (p *Scope) GetEndMinute() (v int32) {
	return p.EndMinute
}

func (p *Scope) GetEditableItemIds() (v []string) {
	return p.EditableItemIds
}

func (p *Scope) GetLockedItemIds() (v []string) {
	return p.LockedItemIds
}
func (p *Scope) SetDate(val string) {
	p.Date = val
}
func (p *Scope) SetStartMinute(val int32) {
	p.StartMinute = val
}
func (p *Scope) SetEndMinute(val int32) {
	p.EndMinute = val
}
func (p *Scope) SetEditableItemIds(val []string) {
	p.EditableItemIds = val
}
func (p *Scope) SetLockedItemIds(val []string) {
	p.LockedItemIds = val
}

func (p *Scope) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Scope(%+v)", *p)
}

var fieldIDToName_Scope = map[int16]string{
	1: "date",
	2: "start_minute",
	3: "end_minute",
	4: "editable_item_ids",
	5: "locked_item_ids",
}

type JobInput struct {
	Constraints     *Constraints `thrift:"constraints,1" frugal:"1,default,Constraints" json:"constraints"`
	ExpectedVersion int64        `thrift:"expected_version,2" frugal:"2,default,i64" json:"expected_version"`
	Scope           *Scope       `thrift:"scope,3,optional" frugal:"3,optional,Scope" json:"scope,omitempty"`
	Instruction     string       `thrift:"instruction,4" frugal:"4,default,string" json:"instruction"`
	Plan            *Plan        `thrift:"plan,5,optional" frugal:"5,optional,Plan" json:"plan,omitempty"`
}

func NewJobInput() *JobInput {
	return &JobInput{}
}

func (p *JobInput) InitDefault() {
}

var JobInput_Constraints_DEFAULT *Constraints

func (p *JobInput) GetConstraints() (v *Constraints) {
	if !p.IsSetConstraints() {
		return JobInput_Constraints_DEFAULT
	}
	return p.Constraints
}

func (p *JobInput) GetExpectedVersion() (v int64) {
	return p.ExpectedVersion
}

var JobInput_Scope_DEFAULT *Scope

func (p *JobInput) GetScope() (v *Scope) {
	if !p.IsSetScope() {
		return JobInput_Scope_DEFAULT
	}
	return p.Scope
}

func (p *JobInput) GetInstruction() (v string) {
	return p.Instruction
}

var JobInput_Plan_DEFAULT *Plan

func (p *JobInput) GetPlan() (v *Plan) {
	if !p.IsSetPlan() {
		return JobInput_Plan_DEFAULT
	}
	return p.Plan
}
func (p *JobInput) SetConstraints(val *Constraints) {
	p.Constraints = val
}
func (p *JobInput) SetExpectedVersion(val int64) {
	p.ExpectedVersion = val
}
func (p *JobInput) SetScope(val *Scope) {
	p.Scope = val
}
func (p *JobInput) SetInstruction(val string) {
	p.Instruction = val
}
func (p *JobInput) SetPlan(val *Plan) {
	p.Plan = val
}

func (p *JobInput) IsSetConstraints() bool {
	return p.Constraints != nil
}

func (p *JobInput) IsSetScope() bool {
	return p.Scope != nil
}

func (p *JobInput) IsSetPlan() bool {
	return p.Plan != nil
}

func (p *JobInput) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("JobInput(%+v)", *p)
}

var fieldIDToName_JobInput = map[int16]string{
	1: "constraints",
	2: "expected_version",
	3: "scope",
	4: "instruction",
	5: "plan",
}

type APIError struct {
	Code        string            `thrift:"code,1" frugal:"1,default,string" json:"code"`
	Message     string            `thrift:"message,2" frugal:"2,default,string" json:"message"`
	Status      int32             `thrift:"status,3" frugal:"3,default,i32" json:"status"`
	FieldErrors map[string]string `thrift:"field_errors,4" frugal:"4,default,map<string:string>" json:"field_errors"`
	RetryAfter  *int32            `thrift:"retry_after,5,optional" frugal:"5,optional,i32" json:"retry_after,omitempty"`
}

func NewAPIError() *APIError {
	return &APIError{}
}

func (p *APIError) InitDefault() {
}

func (p *APIError) GetCode() (v string) {
	return p.Code
}

func (p *APIError) GetMessage() (v string) {
	return p.Message
}

func (p *APIError) GetStatus() (v int32) {
	return p.Status
}

func (p *APIError) GetFieldErrors() (v map[string]string) {
	return p.FieldErrors
}

var APIError_RetryAfter_DEFAULT int32

func (p *APIError) GetRetryAfter() (v int32) {
	if !p.IsSetRetryAfter() {
		return APIError_RetryAfter_DEFAULT
	}
	return *p.RetryAfter
}
func (p *APIError) SetCode(val string) {
	p.Code = val
}
func (p *APIError) SetMessage(val string) {
	p.Message = val
}
func (p *APIError) SetStatus(val int32) {
	p.Status = val
}
func (p *APIError) SetFieldErrors(val map[string]string) {
	p.FieldErrors = val
}
func (p *APIError) SetRetryAfter(val *int32) {
	p.RetryAfter = val
}

func (p *APIError) IsSetRetryAfter() bool {
	return p.RetryAfter != nil
}

func (p *APIError) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("APIError(%+v)", *p)
}

var fieldIDToName_APIError = map[int16]string{
	1: "code",
	2: "message",
	3: "status",
	4: "field_errors",
	5: "retry_after",
}

type ModelRun struct {
	ProviderRequestId string `thrift:"provider_request_id,1" frugal:"1,default,string" json:"provider_request_id"`
	ReturnedModel     string `thrift:"returned_model,2" frugal:"2,default,string" json:"returned_model"`
	PromptVersion     string `thrift:"prompt_version,3" frugal:"3,default,string" json:"prompt_version"`
	DurationMs        int64  `thrift:"duration_ms,4" frugal:"4,default,i64" json:"duration_ms"`
	PromptTokens      *int64 `thrift:"prompt_tokens,5,optional" frugal:"5,optional,i64" json:"prompt_tokens,omitempty"`
	CompletionTokens  *int64 `thrift:"completion_tokens,6,optional" frugal:"6,optional,i64" json:"completion_tokens,omitempty"`
	FinishReason      string `thrift:"finish_reason,7" frugal:"7,default,string" json:"finish_reason"`
}

func NewModelRun() *ModelRun {
	return &ModelRun{}
}

func (p *ModelRun) InitDefault() {
}

func (p *ModelRun) GetProviderRequestId() (v string) {
	return p.ProviderRequestId
}

func (p *ModelRun) GetReturnedModel() (v string) {
	return p.ReturnedModel
}

func (p *ModelRun) GetPromptVersion() (v string) {
	return p.PromptVersion
}

func (p *ModelRun) GetDurationMs() (v int64) {
	return p.DurationMs
}

var ModelRun_PromptTokens_DEFAULT int64

func (p *ModelRun) GetPromptTokens() (v int64) {
	if !p.IsSetPromptTokens() {
		return ModelRun_PromptTokens_DEFAULT
	}
	return *p.PromptTokens
}

var ModelRun_CompletionTokens_DEFAULT int64

func (p *ModelRun) GetCompletionTokens() (v int64) {
	if !p.IsSetCompletionTokens() {
		return ModelRun_CompletionTokens_DEFAULT
	}
	return *p.CompletionTokens
}

func (p *ModelRun) GetFinishReason() (v string) {
	return p.FinishReason
}
func (p *ModelRun) SetProviderRequestId(val string) {
	p.ProviderRequestId = val
}
func (p *ModelRun) SetReturnedModel(val string) {
	p.ReturnedModel = val
}
func (p *ModelRun) SetPromptVersion(val string) {
	p.PromptVersion = val
}
func (p *ModelRun) SetDurationMs(val int64) {
	p.DurationMs = val
}
func (p *ModelRun) SetPromptTokens(val *int64) {
	p.PromptTokens = val
}
func (p *ModelRun) SetCompletionTokens(val *int64) {
	p.CompletionTokens = val
}
func (p *ModelRun) SetFinishReason(val string) {
	p.FinishReason = val
}

func (p *ModelRun) IsSetPromptTokens() bool {
	return p.PromptTokens != nil
}

func (p *ModelRun) IsSetCompletionTokens() bool {
	return p.CompletionTokens != nil
}

func (p *ModelRun) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ModelRun(%+v)", *p)
}

var fieldIDToName_ModelRun = map[int16]string{
	1: "provider_request_id",
	2: "returned_model",
	3: "prompt_version",
	4: "duration_ms",
	5: "prompt_tokens",
	6: "completion_tokens",
	7: "finish_reason",
}

type PlanningRequest struct {
	ServiceToken     string       `thrift:"service_token,1" frugal:"1,default,string" json:"service_token"`
	JobId            string       `thrift:"job_id,2" frugal:"2,default,string" json:"job_id"`
	AttemptId        string       `thrift:"attempt_id,3" frugal:"3,default,string" json:"attempt_id"`
	Constraints      *Constraints `thrift:"constraints,4" frugal:"4,default,Constraints" json:"constraints"`
	Places           []*Place     `thrift:"places,5" frugal:"5,default,list<Place>" json:"places"`
	Base             *Plan        `thrift:"base,6,optional" frugal:"6,optional,Plan" json:"base,omitempty"`
	Scope            *Scope       `thrift:"scope,7,optional" frugal:"7,optional,Scope" json:"scope,omitempty"`
	Instruction      string       `thrift:"instruction,8" frugal:"8,default,string" json:"instruction"`
	PreviousOutput   string       `thrift:"previous_output,9" frugal:"9,default,string" json:"previous_output"`
	ValidationIssues []string     `thrift:"validation_issues,10" frugal:"10,default,list<string>" json:"validation_issues"`
}

func NewPlanningRequest() *PlanningRequest {
	return &PlanningRequest{}
}

func (p *PlanningRequest) InitDefault() {
}

func (p *PlanningRequest) GetServiceToken() (v string) {
	return p.ServiceToken
}

func (p *PlanningRequest) GetJobId() (v string) {
	return p.JobId
}

func (p *PlanningRequest) GetAttemptId() (v string) {
	return p.AttemptId
}

var PlanningRequest_Constraints_DEFAULT *Constraints

func (p *PlanningRequest) GetConstraints() (v *Constraints) {
	if !p.IsSetConstraints() {
		return PlanningRequest_Constraints_DEFAULT
	}
	return p.Constraints
}

func (p *PlanningRequest) GetPlaces() (v []*Place) {
	return p.Places
}

var PlanningRequest_Base_DEFAULT *Plan

func (p *PlanningRequest) GetBase() (v *Plan) {
	if !p.IsSetBase() {
		return PlanningRequest_Base_DEFAULT
	}
	return p.Base
}

var PlanningRequest_Scope_DEFAULT *Scope

func (p *PlanningRequest) GetScope() (v *Scope) {
	if !p.IsSetScope() {
		return PlanningRequest_Scope_DEFAULT
	}
	return p.Scope
}

func (p *PlanningRequest) GetInstruction() (v string) {
	return p.Instruction
}

func (p *PlanningRequest) GetPreviousOutput() (v string) {
	return p.PreviousOutput
}

func (p *PlanningRequest) GetValidationIssues() (v []string) {
	return p.ValidationIssues
}
func (p *PlanningRequest) SetServiceToken(val string) {
	p.ServiceToken = val
}
func (p *PlanningRequest) SetJobId(val string) {
	p.JobId = val
}
func (p *PlanningRequest) SetAttemptId(val string) {
	p.AttemptId = val
}
func (p *PlanningRequest) SetConstraints(val *Constraints) {
	p.Constraints = val
}
func (p *PlanningRequest) SetPlaces(val []*Place) {
	p.Places = val
}
func (p *PlanningRequest) SetBase(val *Plan) {
	p.Base = val
}
func (p *PlanningRequest) SetScope(val *Scope) {
	p.Scope = val
}
func (p *PlanningRequest) SetInstruction(val string) {
	p.Instruction = val
}
func (p *PlanningRequest) SetPreviousOutput(val string) {
	p.PreviousOutput = val
}
func (p *PlanningRequest) SetValidationIssues(val []string) {
	p.ValidationIssues = val
}

func (p *PlanningRequest) IsSetConstraints() bool {
	return p.Constraints != nil
}

func (p *PlanningRequest) IsSetBase() bool {
	return p.Base != nil
}

func (p *PlanningRequest) IsSetScope() bool {
	return p.Scope != nil
}

func (p *PlanningRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PlanningRequest(%+v)", *p)
}

var fieldIDToName_PlanningRequest = map[int16]string{
	1:  "service_token",
	2:  "job_id",
	3:  "attempt_id",
	4:  "constraints",
	5:  "places",
	6:  "base",
	7:  "scope",
	8:  "instruction",
	9:  "previous_output",
	10: "validation_issues",
}

type PlanningResult_ struct {
	Outcome   string    `thrift:"outcome,1" frugal:"1,default,string" json:"outcome"`
	Plan      *Plan     `thrift:"plan,2,optional" frugal:"2,optional,Plan" json:"plan,omitempty"`
	Issues    []string  `thrift:"issues,3" frugal:"3,default,list<string>" json:"issues"`
	RawOutput string    `thrift:"raw_output,4" frugal:"4,default,string" json:"raw_output"`
	ModelRun  *ModelRun `thrift:"model_run,5,optional" frugal:"5,optional,ModelRun" json:"model_run,omitempty"`
	Error     *APIError `thrift:"error,6,optional" frugal:"6,optional,APIError" json:"error,omitempty"`
}

func NewPlanningResult_() *PlanningResult_ {
	return &PlanningResult_{}
}

func (p *PlanningResult_) InitDefault() {
}

func (p *PlanningResult_) GetOutcome() (v string) {
	return p.Outcome
}

var PlanningResult__Plan_DEFAULT *Plan

func (p *PlanningResult_) GetPlan() (v *Plan) {
	if !p.IsSetPlan() {
		return PlanningResult__Plan_DEFAULT
	}
	return p.Plan
}

func (p *PlanningResult_) GetIssues() (v []string) {
	return p.Issues
}

func (p *PlanningResult_) GetRawOutput() (v string) {
	return p.RawOutput
}

var PlanningResult__ModelRun_DEFAULT *ModelRun

func (p *PlanningResult_) GetModelRun() (v *ModelRun) {
	if !p.IsSetModelRun() {
		return PlanningResult__ModelRun_DEFAULT
	}
	return p.ModelRun
}

var PlanningResult__Error_DEFAULT *APIError

func (p *PlanningResult_) GetError() (v *APIError) {
	if !p.IsSetError() {
		return PlanningResult__Error_DEFAULT
	}
	return p.Error
}
func (p *PlanningResult_) SetOutcome(val string) {
	p.Outcome = val
}
func (p *PlanningResult_) SetPlan(val *Plan) {
	p.Plan = val
}
func (p *PlanningResult_) SetIssues(val []string) {
	p.Issues = val
}
func (p *PlanningResult_) SetRawOutput(val string) {
	p.RawOutput = val
}
func (p *PlanningResult_) SetModelRun(val *ModelRun) {
	p.ModelRun = val
}
func (p *PlanningResult_) SetError(val *APIError) {
	p.Error = val
}

func (p *PlanningResult_) IsSetPlan() bool {
	return p.Plan != nil
}

func (p *PlanningResult_) IsSetModelRun() bool {
	return p.ModelRun != nil
}

func (p *PlanningResult_) IsSetError() bool {
	return p.Error != nil
}

func (p *PlanningResult_) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PlanningResult_(%+v)", *p)
}

var fieldIDToName_PlanningResult_ = map[int16]string{
	1: "outcome",
	2: "plan",
	3: "issues",
	4: "raw_output",
	5: "model_run",
	6: "error",
}

type User struct {
	Id            string `thrift:"id,1" frugal:"1,default,string" json:"id"`
	Username      string `thrift:"username,2" frugal:"2,default,string" json:"username"`
	Role          string `thrift:"role,3" frugal:"3,default,string" json:"role"`
	Email         string `thrift:"email,4" frugal:"4,default,string" json:"email"`
	EmailVerified bool   `thrift:"email_verified,5" frugal:"5,default,bool" json:"email_verified"`
}

func NewUser() *User {
	return &User{}
}

func (p *User) InitDefault() {
}

func (p *User) GetId() (v string) {
	return p.Id
}

func (p *User) GetUsername() (v string) {
	return p.Username
}

func (p *User) GetRole() (v string) {
	return p.Role
}

func (p *User) GetEmail() (v string) {
	return p.Email
}

func (p *User) GetEmailVerified() (v bool) {
	return p.EmailVerified
}
func (p *User) SetId(val string) {
	p.Id = val
}
func (p *User) SetUsername(val string) {
	p.Username = val
}
func (p *User) SetRole(val string) {
	p.Role = val
}
func (p *User) SetEmail(val string) {
	p.Email = val
}
func (p *User) SetEmailVerified(val bool) {
	p.EmailVerified = val
}

func (p *User) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("User(%+v)", *p)
}

var fieldIDToName_User = map[int16]string{
	1: "id",
	2: "username",
	3: "role",
	4: "email",
	5: "email_verified",
}

type Session struct {
	Token     string `thrift:"token,1" frugal:"1,default,string" json:"token"`
	ExpiresAt string `thrift:"expires_at,2" frugal:"2,default,string" json:"expires_at"`
	User      *User  `thrift:"user,3" frugal:"3,default,User" json:"user"`
}

func NewSession() *Session {
	return &Session{}
}

func (p *Session) InitDefault() {
}

func (p *Session) GetToken() (v string) {
	return p.Token
}

func (p *Session) GetExpiresAt() (v string) {
	return p.ExpiresAt
}

var Session_User_DEFAULT *User

func (p *Session) GetUser() (v *User) {
	if !p.IsSetUser() {
		return Session_User_DEFAULT
	}
	return p.User
}
func (p *Session) SetToken(val string) {
	p.Token = val
}
func (p *Session) SetExpiresAt(val string) {
	p.ExpiresAt = val
}
func (p *Session) SetUser(val *User) {
	p.User = val
}

func (p *Session) IsSetUser() bool {
	return p.User != nil
}

func (p *Session) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Session(%+v)", *p)
}

var fieldIDToName_Session = map[int16]string{
	1: "token",
	2: "expires_at",
	3: "user",
}

type Job struct {
	Id            string      `thrift:"id,1" frugal:"1,default,string" json:"id"`
	Kind          string      `thrift:"kind,2" frugal:"2,default,string" json:"kind"`
	Status        string      `thrift:"status,3" frugal:"3,default,string" json:"status"`
	Stage         string      `thrift:"stage,4" frugal:"4,default,string" json:"stage"`
	TripId        string      `thrift:"trip_id,5" frugal:"5,default,string" json:"trip_id"`
	ResultVersion int64       `thrift:"result_version,6" frugal:"6,default,i64" json:"result_version"`
	ParentJobId   string      `thrift:"parent_job_id,7" frugal:"7,default,string" json:"parent_job_id"`
	CreatedAt     string      `thrift:"created_at,8" frugal:"8,default,string" json:"created_at"`
	UpdatedAt     string      `thrift:"updated_at,9" frugal:"9,default,string" json:"updated_at"`
	Error         *APIError   `thrift:"error,10,optional" frugal:"10,optional,APIError" json:"error,omitempty"`
	ModelRuns     []*ModelRun `thrift:"model_runs,11" frugal:"11,default,list<ModelRun>" json:"model_runs"`
}

func NewJob() *Job {
	return &Job{}
}

func (p *Job) InitDefault() {
}

func (p *Job) GetId() (v string) {
	return p.Id
}

func (p *Job) GetKind() (v string) {
	return p.Kind
}

func (p *Job) GetStatus() (v string) {
	return p.Status
}

func (p *Job) GetStage() (v string) {
	return p.Stage
}

func (p *Job) GetTripId() (v string) {
	return p.TripId
}

func (p *Job) GetResultVersion() (v int64) {
	return p.ResultVersion
}

func (p *Job) GetParentJobId() (v string) {
	return p.ParentJobId
}

func (p *Job) GetCreatedAt() (v string) {
	return p.CreatedAt
}

func (p *Job) GetUpdatedAt() (v string) {
	return p.UpdatedAt
}

var Job_Error_DEFAULT *APIError

func (p *Job) GetError() (v *APIError) {
	if !p.IsSetError() {
		return Job_Error_DEFAULT
	}
	return p.Error
}

func (p *Job) GetModelRuns() (v []*ModelRun) {
	return p.ModelRuns
}
func (p *Job) SetId(val string) {
	p.Id = val
}
func (p *Job) SetKind(val string) {
	p.Kind = val
}
func (p *Job) SetStatus(val string) {
	p.Status = val
}
func (p *Job) SetStage(val string) {
	p.Stage = val
}
func (p *Job) SetTripId(val string) {
	p.TripId = val
}
func (p *Job) SetResultVersion(val int64) {
	p.ResultVersion = val
}
func (p *Job) SetParentJobId(val string) {
	p.ParentJobId = val
}
func (p *Job) SetCreatedAt(val string) {
	p.CreatedAt = val
}
func (p *Job) SetUpdatedAt(val string) {
	p.UpdatedAt = val
}
func (p *Job) SetError(val *APIError) {
	p.Error = val
}
func (p *Job) SetModelRuns(val []*ModelRun) {
	p.ModelRuns = val
}

func (p *Job) IsSetError() bool {
	return p.Error != nil
}

func (p *Job) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Job(%+v)", *p)
}

var fieldIDToName_Job = map[int16]string{
	1:  "id",
	2:  "kind",
	3:  "status",
	4:  "stage",
	5:  "trip_id",
	6:  "result_version",
	7:  "parent_job_id",
	8:  "created_at",
	9:  "updated_at",
	10: "error",
	11: "model_runs",
}

type Trip struct {
	Id          string       `thrift:"id,1" frugal:"1,default,string" json:"id"`
	Version     int64        `thrift:"version,2" frugal:"2,default,i64" json:"version"`
	Constraints *Constraints `thrift:"constraints,3" frugal:"3,default,Constraints" json:"constraints"`
	Plan        *Plan        `thrift:"plan,4" frugal:"4,default,Plan" json:"plan"`
	CreatedAt   string       `thrift:"created_at,5" frugal:"5,default,string" json:"created_at"`
}

func NewTrip() *Trip {
	return &Trip{}
}

func (p *Trip) InitDefault() {
}

func (p *Trip) GetId() (v string) {
	return p.Id
}

func (p *Trip) GetVersion() (v int64) {
	return p.Version
}

var Trip_Constraints_DEFAULT *Constraints

func (p *Trip) GetConstraints() (v *Constraints) {
	if !p.IsSetConstraints() {
		return Trip_Constraints_DEFAULT
	}
	return p.Constraints
}

var Trip_Plan_DEFAULT *Plan

func (p *Trip) GetPlan() (v *Plan) {
	if !p.IsSetPlan() {
		return Trip_Plan_DEFAULT
	}
	return p.Plan
}

func (p *Trip) GetCreatedAt() (v string) {
	return p.CreatedAt
}
func (p *Trip) SetId(val string) {
	p.Id = val
}
func (p *Trip) SetVersion(val int64) {
	p.Version = val
}
func (p *Trip) SetConstraints(val *Constraints) {
	p.Constraints = val
}
func (p *Trip) SetPlan(val *Plan) {
	p.Plan = val
}
func (p *Trip) SetCreatedAt(val string) {
	p.CreatedAt = val
}

func (p *Trip) IsSetConstraints() bool {
	return p.Constraints != nil
}

func (p *Trip) IsSetPlan() bool {
	return p.Plan != nil
}

func (p *Trip) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Trip(%+v)", *p)
}

var fieldIDToName_Trip = map[int16]string{
	1: "id",
	2: "version",
	3: "constraints",
	4: "plan",
	5: "created_at",
}

type AmountGroup struct {
	Key          string `thrift:"key,1" frugal:"1,default,string" json:"key"`
	KnownCents   int64  `thrift:"known_cents,2" frugal:"2,default,i64" json:"known_cents"`
	UnknownCount int32  `thrift:"unknown_count,3" frugal:"3,default,i32" json:"unknown_count"`
}

func NewAmountGroup() *AmountGroup {
	return &AmountGroup{}
}

func (p *AmountGroup) InitDefault() {
}

func (p *AmountGroup) GetKey() (v string) {
	return p.Key
}

func (p *AmountGroup) GetKnownCents() (v int64) {
	return p.KnownCents
}

func (p *AmountGroup) GetUnknownCount() (v int32) {
	return p.UnknownCount
}
func (p *AmountGroup) SetKey(val string) {
	p.Key = val
}
func (p *AmountGroup) SetKnownCents(val int64) {
	p.KnownCents = val
}
func (p *AmountGroup) SetUnknownCount(val int32) {
	p.UnknownCount = val
}

func (p *AmountGroup) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AmountGroup(%+v)", *p)
}

var fieldIDToName_AmountGroup = map[int16]string{
	1: "key",
	2: "known_cents",
	3: "unknown_count",
}

type BudgetSummary struct {
	TripId           string         `thrift:"trip_id,1" frugal:"1,default,string" json:"trip_id"`
	Version          int64          `thrift:"version,2" frugal:"2,default,i64" json:"version"`
	BudgetTotalCents int64          `thrift:"budget_total_cents,3" frugal:"3,default,i64" json:"budget_total_cents"`
	KnownTotalCents  int64          `thrift:"known_total_cents,4" frugal:"4,default,i64" json:"known_total_cents"`
	UnknownCount     int32          `thrift:"unknown_count,5" frugal:"5,default,i32" json:"unknown_count"`
	Complete         bool           `thrift:"complete,6" frugal:"6,default,bool" json:"complete"`
	WithinBudget     *bool          `thrift:"within_budget,7,optional" frugal:"7,optional,bool" json:"within_budget,omitempty"`
	ByDay            []*AmountGroup `thrift:"by_day,8" frugal:"8,default,list<AmountGroup>" json:"by_day"`
	ByCategory       []*AmountGroup `thrift:"by_category,9" frugal:"9,default,list<AmountGroup>" json:"by_category"`
}

func NewBudgetSummary() *BudgetSummary {
	return &BudgetSummary{}
}

func (p *BudgetSummary) InitDefault() {
}

func (p *BudgetSummary) GetTripId() (v string) {
	return p.TripId
}

func (p *BudgetSummary) GetVersion() (v int64) {
	return p.Version
}

func (p *BudgetSummary) GetBudgetTotalCents() (v int64) {
	return p.BudgetTotalCents
}

func (p *BudgetSummary) GetKnownTotalCents() (v int64) {
	return p.KnownTotalCents
}

func (p *BudgetSummary) GetUnknownCount() (v int32) {
	return p.UnknownCount
}

func (p *BudgetSummary) GetComplete() (v bool) {
	return p.Complete
}

var BudgetSummary_WithinBudget_DEFAULT bool

func (p *BudgetSummary) GetWithinBudget() (v bool) {
	if !p.IsSetWithinBudget() {
		return BudgetSummary_WithinBudget_DEFAULT
	}
	return *p.WithinBudget
}

func (p *BudgetSummary) GetByDay() (v []*AmountGroup) {
	return p.ByDay
}

func (p *BudgetSummary) GetByCategory() (v []*AmountGroup) {
	return p.ByCategory
}
func (p *BudgetSummary) SetTripId(val string) {
	p.TripId = val
}
func (p *BudgetSummary) SetVersion(val int64) {
	p.Version = val
}
func (p *BudgetSummary) SetBudgetTotalCents(val int64) {
	p.BudgetTotalCents = val
}
func (p *BudgetSummary) SetKnownTotalCents(val int64) {
	p.KnownTotalCents = val
}
func (p *BudgetSummary) SetUnknownCount(val int32) {
	p.UnknownCount = val
}
func (p *BudgetSummary) SetComplete(val bool) {
	p.Complete = val
}
func (p *BudgetSummary) SetWithinBudget(val *bool) {
	p.WithinBudget = val
}
func (p *BudgetSummary) SetByDay(val []*AmountGroup) {
	p.ByDay = val
}
func (p *BudgetSummary) SetByCategory(val []*AmountGroup) {
	p.ByCategory = val
}

func (p *BudgetSummary) IsSetWithinBudget() bool {
	return p.WithinBudget != nil
}

func (p *BudgetSummary) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BudgetSummary(%+v)", *p)
}

var fieldIDToName_BudgetSummary = map[int16]string{
	1: "trip_id",
	2: "version",
	3: "budget_total_cents",
	4: "known_total_cents",
	5: "unknown_count",
	6: "complete",
	7: "within_budget",
	8: "by_day",
	9: "by_category",
}

type Request struct {
	Token          string    `thrift:"token,1" frugal:"1,default,string" json:"token"`
	RequestId      string    `thrift:"request_id,2" frugal:"2,default,string" json:"request_id"`
	Username       string    `thrift:"username,3" frugal:"3,default,string" json:"username"`
	Password       string    `thrift:"password,4" frugal:"4,default,string" json:"password"`
	Id             string    `thrift:"id,5" frugal:"5,default,string" json:"id"`
	Version        int64     `thrift:"version,6" frugal:"6,default,i64" json:"version"`
	City           string    `thrift:"city,7" frugal:"7,default,string" json:"city"`
	Keyword        string    `thrift:"keyword,8" frugal:"8,default,string" json:"keyword"`
	Page           int32     `thrift:"page,9" frugal:"9,default,i32" json:"page"`
	PageSize       int32     `thrift:"page_size,10" frugal:"10,default,i32" json:"page_size"`
	IdempotencyKey string    `thrift:"idempotency_key,11" frugal:"11,default,string" json:"idempotency_key"`
	Input          *JobInput `thrift:"input,12,optional" frugal:"12,optional,JobInput" json:"input,omitempty"`
	Place          *Place    `thrift:"place,13,optional" frugal:"13,optional,Place" json:"place,omitempty"`
	Email          string    `thrift:"email,14" frugal:"14,default,string" json:"email"`
	Code           string    `thrift:"code,15" frugal:"15,default,string" json:"code"`
	ChallengeId    string    `thrift:"challenge_id,16" frugal:"16,default,string" json:"challenge_id"`
	ClientIp       string    `thrift:"client_ip,17" frugal:"17,default,string" json:"client_ip"`
}

func NewRequest() *Request {
	return &Request{}
}

func (p *Request) InitDefault() {
}

func (p *Request) GetToken() (v string) {
	return p.Token
}

func (p *Request) GetRequestId() (v string) {
	return p.RequestId
}

func (p *Request) GetUsername() (v string) {
	return p.Username
}

func (p *Request) GetPassword() (v string) {
	return p.Password
}

func (p *Request) GetId() (v string) {
	return p.Id
}

func (p *Request) GetVersion() (v int64) {
	return p.Version
}

func (p *Request) GetCity() (v string) {
	return p.City
}

func (p *Request) GetKeyword() (v string) {
	return p.Keyword
}

func (p *Request) GetPage() (v int32) {
	return p.Page
}

func (p *Request) GetPageSize() (v int32) {
	return p.PageSize
}

func (p *Request) GetIdempotencyKey() (v string) {
	return p.IdempotencyKey
}

var Request_Input_DEFAULT *JobInput

func (p *Request) GetInput() (v *JobInput) {
	if !p.IsSetInput() {
		return Request_Input_DEFAULT
	}
	return p.Input
}

var Request_Place_DEFAULT *Place

func (p *Request) GetPlace() (v *Place) {
	if !p.IsSetPlace() {
		return Request_Place_DEFAULT
	}
	return p.Place
}

func (p *Request) GetEmail() (v string) {
	return p.Email
}

func (p *Request) GetCode() (v string) {
	return p.Code
}

func (p *Request) GetChallengeId() (v string) {
	return p.ChallengeId
}

func (p *Request) GetClientIp() (v string) {
	return p.ClientIp
}
func (p *Request) SetToken(val string) {
	p.Token = val
}
func (p *Request) SetRequestId(val string) {
	p.RequestId = val
}
func (p *Request) SetUsername(val string) {
	p.Username = val
}
func (p *Request) SetPassword(val string) {
	p.Password = val
}
func (p *Request) SetId(val string) {
	p.Id = val
}
func (p *Request) SetVersion(val int64) {
	p.Version = val
}
func (p *Request) SetCity(val string) {
	p.City = val
}
func (p *Request) SetKeyword(val string) {
	p.Keyword = val
}
func (p *Request) SetPage(val int32) {
	p.Page = val
}
func (p *Request) SetPageSize(val int32) {
	p.PageSize = val
}
func (p *Request) SetIdempotencyKey(val string) {
	p.IdempotencyKey = val
}
func (p *Request) SetInput(val *JobInput) {
	p.Input = val
}
func (p *Request) SetPlace(val *Place) {
	p.Place = val
}
func (p *Request) SetEmail(val string) {
	p.Email = val
}
func (p *Request) SetCode(val string) {
	p.Code = val
}
func (p *Request) SetChallengeId(val string) {
	p.ChallengeId = val
}
func (p *Request) SetClientIp(val string) {
	p.ClientIp = val
}

func (p *Request) IsSetInput() bool {
	return p.Input != nil
}

func (p *Request) IsSetPlace() bool {
	return p.Place != nil
}

func (p *Request) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Request(%+v)", *p)
}

var fieldIDToName_Request = map[int16]string{
	1:  "token",
	2:  "request_id",
	3:  "username",
	4:  "password",
	5:  "id",
	6:  "version",
	7:  "city",
	8:  "keyword",
	9:  "page",
	10: "page_size",
	11: "idempotency_key",
	12: "input",
	13: "place",
	14: "email",
	15: "code",
	16: "challenge_id",
	17: "client_ip",
}

type Response struct {
	Error     *APIError       `thrift:"error,1,optional" frugal:"1,optional,APIError" json:"error,omitempty"`
	User      *User           `thrift:"user,2,optional" frugal:"2,optional,User" json:"user,omitempty"`
	Session   *Session        `thrift:"session,3,optional" frugal:"3,optional,Session" json:"session,omitempty"`
	Job       *Job            `thrift:"job,4,optional" frugal:"4,optional,Job" json:"job,omitempty"`
	Trip      *Trip           `thrift:"trip,5,optional" frugal:"5,optional,Trip" json:"trip,omitempty"`
	Places    []*Place        `thrift:"places,6" frugal:"6,default,list<Place>" json:"places"`
	Trips     []*Trip         `thrift:"trips,7" frugal:"7,default,list<Trip>" json:"trips"`
	Budget    *BudgetSummary  `thrift:"budget,8,optional" frugal:"8,optional,BudgetSummary" json:"budget,omitempty"`
	Page      int32           `thrift:"page,9" frugal:"9,default,i32" json:"page"`
	PageSize  int32           `thrift:"page_size,10" frugal:"10,default,i32" json:"page_size"`
	HasMore   bool            `thrift:"has_more,11" frugal:"11,default,bool" json:"has_more"`
	Challenge *EmailChallenge `thrift:"challenge,12,optional" frugal:"12,optional,EmailChallenge" json:"challenge,omitempty"`
}

func NewResponse() *Response {
	return &Response{}
}

func (p *Response) InitDefault() {
}

var Response_Error_DEFAULT *APIError

func (p *Response) GetError() (v *APIError) {
	if !p.IsSetError() {
		return Response_Error_DEFAULT
	}
	return p.Error
}

var Response_User_DEFAULT *User

func (p *Response) GetUser() (v *User) {
	if !p.IsSetUser() {
		return Response_User_DEFAULT
	}
	return p.User
}

var Response_Session_DEFAULT *Session

func (p *Response) GetSession() (v *Session) {
	if !p.IsSetSession() {
		return Response_Session_DEFAULT
	}
	return p.Session
}

var Response_Job_DEFAULT *Job

func (p *Response) GetJob() (v *Job) {
	if !p.IsSetJob() {
		return Response_Job_DEFAULT
	}
	return p.Job
}

var Response_Trip_DEFAULT *Trip

func (p *Response) GetTrip() (v *Trip) {
	if !p.IsSetTrip() {
		return Response_Trip_DEFAULT
	}
	return p.Trip
}

func (p *Response) GetPlaces() (v []*Place) {
	return p.Places
}

func (p *Response) GetTrips() (v []*Trip) {
	return p.Trips
}

var Response_Budget_DEFAULT *BudgetSummary

func (p *Response) GetBudget() (v *BudgetSummary) {
	if !p.IsSetBudget() {
		return Response_Budget_DEFAULT
	}
	return p.Budget
}

func (p *Response) GetPage() (v int32) {
	return p.Page
}

func (p *Response) GetPageSize() (v int32) {
	return p.PageSize
}

func (p *Response) GetHasMore() (v bool) {
	return p.HasMore
}

var Response_Challenge_DEFAULT *EmailChallenge

func (p *Response) GetChallenge() (v *EmailChallenge) {
	if !p.IsSetChallenge() {
		return Response_Challenge_DEFAULT
	}
	return p.Challenge
}
func (p *Response) SetError(val *APIError) {
	p.Error = val
}
func (p *Response) SetUser(val *User) {
	p.User = val
}
func (p *Response) SetSession(val *Session) {
	p.Session = val
}
func (p *Response) SetJob(val *Job) {
	p.Job = val
}
func (p *Response) SetTrip(val *Trip) {
	p.Trip = val
}
func (p *Response) SetPlaces(val []*Place) {
	p.Places = val
}
func (p *Response) SetTrips(val []*Trip) {
	p.Trips = val
}
func (p *Response) SetBudget(val *BudgetSummary) {
	p.Budget = val
}
func (p *Response) SetPage(val int32) {
	p.Page = val
}
func (p *Response) SetPageSize(val int32) {
	p.PageSize = val
}
func (p *Response) SetHasMore(val bool) {
	p.HasMore = val
}
func (p *Response) SetChallenge(val *EmailChallenge) {
	p.Challenge = val
}

func (p *Response) IsSetError() bool {
	return p.Error != nil
}

func (p *Response) IsSetUser() bool {
	return p.User != nil
}

func (p *Response) IsSetSession() bool {
	return p.Session != nil
}

func (p *Response) IsSetJob() bool {
	return p.Job != nil
}

func (p *Response) IsSetTrip() bool {
	return p.Trip != nil
}

func (p *Response) IsSetBudget() bool {
	return p.Budget != nil
}

func (p *Response) IsSetChallenge() bool {
	return p.Challenge != nil
}

func (p *Response) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Response(%+v)", *p)
}

var fieldIDToName_Response = map[int16]string{
	1:  "error",
	2:  "user",
	3:  "session",
	4:  "job",
	5:  "trip",
	6:  "places",
	7:  "trips",
	8:  "budget",
	9:  "page",
	10: "page_size",
	11: "has_more",
	12: "challenge",
}

type EmailChallenge struct {
	ChallengeId string `thrift:"challenge_id,1" frugal:"1,default,string" json:"challenge_id"`
	ExpiresIn   int32  `thrift:"expires_in,2" frugal:"2,default,i32" json:"expires_in"`
	RetryAfter  int32  `thrift:"retry_after,3" frugal:"3,default,i32" json:"retry_after"`
}

func NewEmailChallenge() *EmailChallenge {
	return &EmailChallenge{}
}

func (p *EmailChallenge) InitDefault() {
}

func (p *EmailChallenge) GetChallengeId() (v string) {
	return p.ChallengeId
}

func (p *EmailChallenge) GetExpiresIn() (v int32) {
	return p.ExpiresIn
}

func (p *EmailChallenge) GetRetryAfter() (v int32) {
	return p.RetryAfter
}
func (p *EmailChallenge) SetChallengeId(val string) {
	p.ChallengeId = val
}
func (p *EmailChallenge) SetExpiresIn(val int32) {
	p.ExpiresIn = val
}
func (p *EmailChallenge) SetRetryAfter(val int32) {
	p.RetryAfter = val
}

func (p *EmailChallenge) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("EmailChallenge(%+v)", *p)
}

var fieldIDToName_EmailChallenge = map[int16]string{
	1: "challenge_id",
	2: "expires_in",
	3: "retry_after",
}
