// Code generated by Kitex v0.16.3. DO NOT EDIT.

package travelservice

import (
	model "ai-travel/kitex_gen/model"
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Register(ctx context.Context, req *model.Request, callOptions ...callopt.Option) (r *model.Response, err error)
	Login(ctx context.Context, req *model.Request, callOptions ...callopt.Option) (r *model.Response, err error)
	Logout(ctx context.Context, req *model.Request, callOptions ...callopt.Option) (r *model.Response, err error)
	GetCurrentUser(ctx context.Context, req *model.Request, callOptions ...callopt.Option) (r *model.Response, err error)
	SearchPlaces(ctx context.Context, req *model.Request, callOptions ...callopt.Option) (r *model.Response, err error)
	CreatePlace(ctx context.Context, req *model.Request, callOptions ...callopt.Option) (r *model.Response, err error)
	UpdatePlace(ctx context.Context, req *model.Request, callOptions ...callopt.Option) (r *model.Response, err error)
	CreatePlanningJob(ctx context.Context, req *model.Request, callOptions ...callopt.Option) (r *model.Response, err error)
	GetPlanningJob(ctx context.Context, req *model.Request, callOptions ...callopt.Option) (r *model.Response, err error)
	RetryPlanningJob(ctx context.Context, req *model.Request, callOptions ...callopt.Option) (r *model.Response, err error)
	ListTrips(ctx context.Context, req *model.Request, callOptions ...callopt.Option) (r *model.Response, err error)
	GetTrip(ctx context.Context, req *model.Request, callOptions ...callopt.Option) (r *model.Response, err error)
	UpdateTrip(ctx context.Context, req *model.Request, callOptions ...callopt.Option) (r *model.Response, err error)
	CreateReplanningJob(ctx context.Context, req *model.Request, callOptions ...callopt.Option) (r *model.Response, err error)
	ListTripVersions(ctx context.Context, req *model.Request, callOptions ...callopt.Option) (r *model.Response, err error)
	GetTripVersion(ctx context.Context, req *model.Request, callOptions ...callopt.Option) (r *model.Response, err error)
	GetBudgetSummary(ctx context.Context, req *model.Request, callOptions ...callopt.Option) (r *model.Response, err error)
	Health(ctx context.Context, req *model.Request, callOptions ...callopt.Option) (r *model.Response, err error)
	RequestRegistrationCode(ctx context.Context, req *model.Request, callOptions ...callopt.Option) (r *model.Response, err error)
	LegacyLogin(ctx context.Context, req *model.Request, callOptions ...callopt.Option) (r *model.Response, err error)
	RequestEmailBindingCode(ctx context.Context, req *model.Request, callOptions ...callopt.Option) (r *model.Response, err error)
	BindEmail(ctx context.Context, req *model.Request, callOptions ...callopt.Option) (r *model.Response, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kTravelServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kTravelServiceClient struct {
	*kClient
}

func (p *kTravelServiceClient) Register(ctx context.Context, req *model.Request, callOptions ...callopt.Option) (r *model.Response, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Register(ctx, req)
}

func (p *kTravelServiceClient) Login(ctx context.Context, req *model.Request, callOptions ...callopt.Option) (r *model.Response, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Login(ctx, req)
}

func (p *kTravelServiceClient) Logout(ctx context.Context, req *model.Request, callOptions ...callopt.Option) (r *model.Response, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Logout(ctx, req)
}

func (p *kTravelServiceClient) GetCurrentUser(ctx context.Context, req *model.Request, callOptions ...callopt.Option) (r *model.Response, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetCurrentUser(ctx, req)
}

func (p *kTravelServiceClient) SearchPlaces(ctx context.Context, req *model.Request, callOptions ...callopt.Option) (r *model.Response, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SearchPlaces(ctx, req)
}

func (p *kTravelServiceClient) CreatePlace(ctx context.Context, req *model.Request, callOptions ...callopt.Option) (r *model.Response, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreatePlace(ctx, req)
}

func (p *kTravelServiceClient) UpdatePlace(ctx context.Context, req *model.Request, callOptions ...callopt.Option) (r *model.Response, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdatePlace(ctx, req)
}

func (p *kTravelServiceClient) CreatePlanningJob(ctx context.Context, req *model.Request, callOptions ...callopt.Option) (r *model.Response, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreatePlanningJob(ctx, req)
}

func (p *kTravelServiceClient) GetPlanningJob(ctx context.Context, req *model.Request, callOptions ...callopt.Option) (r *model.Response, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetPlanningJob(ctx, req)
}

func (p *kTravelServiceClient) RetryPlanningJob(ctx context.Context, req *model.Request, callOptions ...callopt.Option) (r *model.Response, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.RetryPlanningJob(ctx, req)
}

func (p *kTravelServiceClient) ListTrips(ctx context.Context, req *model.Request, callOptions ...callopt.Option) (r *model.Response, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListTrips(ctx, req)
}

func (p *kTravelServiceClient) GetTrip(ctx context.Context, req *model.Request, callOptions ...callopt.Option) (r *model.Response, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetTrip(ctx, req)
}

func (p *kTravelServiceClient) UpdateTrip(ctx context.Context, req *model.Request, callOptions ...callopt.Option) (r *model.Response, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateTrip(ctx, req)
}

func (p *kTravelServiceClient) CreateReplanningJob(ctx context.Context, req *model.Request, callOptions ...callopt.Option) (r *model.Response, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateReplanningJob(ctx, req)
}

func (p *kTravelServiceClient) ListTripVersions(ctx context.Context, req *model.Request, callOptions ...callopt.Option) (r *model.Response, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListTripVersions(ctx, req)
}

func (p *kTravelServiceClient) GetTripVersion(ctx context.Context, req *model.Request, callOptions ...callopt.Option) (r *model.Response, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetTripVersion(ctx, req)
}

func (p *kTravelServiceClient) GetBudgetSummary(ctx context.Context, req *model.Request, callOptions ...callopt.Option) (r *model.Response, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetBudgetSummary(ctx, req)
}

func (p *kTravelServiceClient) Health(ctx context.Context, req *model.Request, callOptions ...callopt.Option) (r *model.Response, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Health(ctx, req)
}

func (p *kTravelServiceClient) RequestRegistrationCode(ctx context.Context, req *model.Request, callOptions ...callopt.Option) (r *model.Response, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.RequestRegistrationCode(ctx, req)
}

func (p *kTravelServiceClient) LegacyLogin(ctx context.Context, req *model.Request, callOptions ...callopt.Option) (r *model.Response, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.LegacyLogin(ctx, req)
}

func (p *kTravelServiceClient) RequestEmailBindingCode(ctx context.Context, req *model.Request, callOptions ...callopt.Option) (r *model.Response, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.RequestEmailBindingCode(ctx, req)
}

func (p *kTravelServiceClient) BindEmail(ctx context.Context, req *model.Request, callOptions ...callopt.Option) (r *model.Response, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.BindEmail(ctx, req)
}
