// Code generated by Kitex v0.16.3. DO NOT EDIT.

package travelservice

import (
	model "ai-travel/kitex_gen/model"
	travel "ai-travel/kitex_gen/travel"
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"Register": kitex.NewMethodInfo(
		registerHandler,
		newTravelServiceRegisterArgs,
		newTravelServiceRegisterResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Login": kitex.NewMethodInfo(
		loginHandler,
		newTravelServiceLoginArgs,
		newTravelServiceLoginResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Logout": kitex.NewMethodInfo(
		logoutHandler,
		newTravelServiceLogoutArgs,
		newTravelServiceLogoutResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetCurrentUser": kitex.NewMethodInfo(
		getCurrentUserHandler,
		newTravelServiceGetCurrentUserArgs,
		newTravelServiceGetCurrentUserResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"SearchPlaces": kitex.NewMethodInfo(
		searchPlacesHandler,
		newTravelServiceSearchPlacesArgs,
		newTravelServiceSearchPlacesResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"CreatePlace": kitex.NewMethodInfo(
		createPlaceHandler,
		newTravelServiceCreatePlaceArgs,
		newTravelServiceCreatePlaceResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"UpdatePlace": kitex.NewMethodInfo(
		updatePlaceHandler,
		newTravelServiceUpdatePlaceArgs,
		newTravelServiceUpdatePlaceResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"CreatePlanningJob": kitex.NewMethodInfo(
		createPlanningJobHandler,
		newTravelServiceCreatePlanningJobArgs,
		newTravelServiceCreatePlanningJobResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetPlanningJob": kitex.NewMethodInfo(
		getPlanningJobHandler,
		newTravelServiceGetPlanningJobArgs,
		newTravelServiceGetPlanningJobResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"RetryPlanningJob": kitex.NewMethodInfo(
		retryPlanningJobHandler,
		newTravelServiceRetryPlanningJobArgs,
		newTravelServiceRetryPlanningJobResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ListTrips": kitex.NewMethodInfo(
		listTripsHandler,
		newTravelServiceListTripsArgs,
		newTravelServiceListTripsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetTrip": kitex.NewMethodInfo(
		getTripHandler,
		newTravelServiceGetTripArgs,
		newTravelServiceGetTripResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"UpdateTrip": kitex.NewMethodInfo(
		updateTripHandler,
		newTravelServiceUpdateTripArgs,
		newTravelServiceUpdateTripResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"CreateReplanningJob": kitex.NewMethodInfo(
		createReplanningJobHandler,
		newTravelServiceCreateReplanningJobArgs,
		newTravelServiceCreateReplanningJobResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ListTripVersions": kitex.NewMethodInfo(
		listTripVersionsHandler,
		newTravelServiceListTripVersionsArgs,
		newTravelServiceListTripVersionsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetTripVersion": kitex.NewMethodInfo(
		getTripVersionHandler,
		newTravelServiceGetTripVersionArgs,
		newTravelServiceGetTripVersionResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetBudgetSummary": kitex.NewMethodInfo(
		getBudgetSummaryHandler,
		newTravelServiceGetBudgetSummaryArgs,
		newTravelServiceGetBudgetSummaryResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Health": kitex.NewMethodInfo(
		healthHandler,
		newTravelServiceHealthArgs,
		newTravelServiceHealthResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"RequestRegistrationCode": kitex.NewMethodInfo(
		requestRegistrationCodeHandler,
		newTravelServiceRequestRegistrationCodeArgs,
		newTravelServiceRequestRegistrationCodeResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"LegacyLogin": kitex.NewMethodInfo(
		legacyLoginHandler,
		newTravelServiceLegacyLoginArgs,
		newTravelServiceLegacyLoginResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"RequestEmailBindingCode": kitex.NewMethodInfo(
		requestEmailBindingCodeHandler,
		newTravelServiceRequestEmailBindingCodeArgs,
		newTravelServiceRequestEmailBindingCodeResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"BindEmail": kitex.NewMethodInfo(
		bindEmailHandler,
		newTravelServiceBindEmailArgs,
		newTravelServiceBindEmailResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	travelServiceServiceInfo                = NewServiceInfo()
	travelServiceServiceInfoForClient       = NewServiceInfoForClient()
	travelServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return travelServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return travelServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return travelServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "TravelService"
	handlerType := (*travel.TravelService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "travel",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.16.3",
		Extra:           extra,
	}
	return svcInfo
}

func registerHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*travel.TravelServiceRegisterArgs)
	realResult := result.(*travel.TravelServiceRegisterResult)
	success, err := handler.(travel.TravelService).Register(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newTravelServiceRegisterArgs() interface{} {
	return travel.NewTravelServiceRegisterArgs()
}

func newTravelServiceRegisterResult() interface{} {
	return travel.NewTravelServiceRegisterResult()
}

func loginHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*travel.TravelServiceLoginArgs)
	realResult := result.(*travel.TravelServiceLoginResult)
	success, err := handler.(travel.TravelService).Login(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newTravelServiceLoginArgs() interface{} {
	return travel.NewTravelServiceLoginArgs()
}

func newTravelServiceLoginResult() interface{} {
	return travel.NewTravelServiceLoginResult()
}

func logoutHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*travel.TravelServiceLogoutArgs)
	realResult := result.(*travel.TravelServiceLogoutResult)
	success, err := handler.(travel.TravelService).Logout(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newTravelServiceLogoutArgs() interface{} {
	return travel.NewTravelServiceLogoutArgs()
}

func newTravelServiceLogoutResult() interface{} {
	return travel.NewTravelServiceLogoutResult()
}

func getCurrentUserHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*travel.TravelServiceGetCurrentUserArgs)
	realResult := result.(*travel.TravelServiceGetCurrentUserResult)
	success, err := handler.(travel.TravelService).GetCurrentUser(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newTravelServiceGetCurrentUserArgs() interface{} {
	return travel.NewTravelServiceGetCurrentUserArgs()
}

func newTravelServiceGetCurrentUserResult() interface{} {
	return travel.NewTravelServiceGetCurrentUserResult()
}

func searchPlacesHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*travel.TravelServiceSearchPlacesArgs)
	realResult := result.(*travel.TravelServiceSearchPlacesResult)
	success, err := handler.(travel.TravelService).SearchPlaces(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newTravelServiceSearchPlacesArgs() interface{} {
	return travel.NewTravelServiceSearchPlacesArgs()
}

func newTravelServiceSearchPlacesResult() interface{} {
	return travel.NewTravelServiceSearchPlacesResult()
}

func createPlaceHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*travel.TravelServiceCreatePlaceArgs)
	realResult := result.(*travel.TravelServiceCreatePlaceResult)
	success, err := handler.(travel.TravelService).CreatePlace(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newTravelServiceCreatePlaceArgs() interface{} {
	return travel.NewTravelServiceCreatePlaceArgs()
}

func newTravelServiceCreatePlaceResult() interface{} {
	return travel.NewTravelServiceCreatePlaceResult()
}

func updatePlaceHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*travel.TravelServiceUpdatePlaceArgs)
	realResult := result.(*travel.TravelServiceUpdatePlaceResult)
	success, err := handler.(travel.TravelService).UpdatePlace(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newTravelServiceUpdatePlaceArgs() interface{} {
	return travel.NewTravelServiceUpdatePlaceArgs()
}

func newTravelServiceUpdatePlaceResult() interface{} {
	return travel.NewTravelServiceUpdatePlaceResult()
}

func createPlanningJobHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*travel.TravelServiceCreatePlanningJobArgs)
	realResult := result.(*travel.TravelServiceCreatePlanningJobResult)
	success, err := handler.(travel.TravelService).CreatePlanningJob(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newTravelServiceCreatePlanningJobArgs() interface{} {
	return travel.NewTravelServiceCreatePlanningJobArgs()
}

func newTravelServiceCreatePlanningJobResult() interface{} {
	return travel.NewTravelServiceCreatePlanningJobResult()
}

func getPlanningJobHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*travel.TravelServiceGetPlanningJobArgs)
	realResult := result.(*travel.TravelServiceGetPlanningJobResult)
	success, err := handler.(travel.TravelService).GetPlanningJob(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newTravelServiceGetPlanningJobArgs() interface{} {
	return travel.NewTravelServiceGetPlanningJobArgs()
}

func newTravelServiceGetPlanningJobResult() interface{} {
	return travel.NewTravelServiceGetPlanningJobResult()
}

func retryPlanningJobHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*travel.TravelServiceRetryPlanningJobArgs)
	realResult := result.(*travel.TravelServiceRetryPlanningJobResult)
	success, err := handler.(travel.TravelService).RetryPlanningJob(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newTravelServiceRetryPlanningJobArgs() interface{} {
	return travel.NewTravelServiceRetryPlanningJobArgs()
}

func newTravelServiceRetryPlanningJobResult() interface{} {
	return travel.NewTravelServiceRetryPlanningJobResult()
}

func listTripsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*travel.TravelServiceListTripsArgs)
	realResult := result.(*travel.TravelServiceListTripsResult)
	success, err := handler.(travel.TravelService).ListTrips(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newTravelServiceListTripsArgs() interface{} {
	return travel.NewTravelServiceListTripsArgs()
}

func newTravelServiceListTripsResult() interface{} {
	return travel.NewTravelServiceListTripsResult()
}

func getTripHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*travel.TravelServiceGetTripArgs)
	realResult := result.(*travel.TravelServiceGetTripResult)
	success, err := handler.(travel.TravelService).GetTrip(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newTravelServiceGetTripArgs() interface{} {
	return travel.NewTravelServiceGetTripArgs()
}

func newTravelServiceGetTripResult() interface{} {
	return travel.NewTravelServiceGetTripResult()
}

func updateTripHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*travel.TravelServiceUpdateTripArgs)
	realResult := result.(*travel.TravelServiceUpdateTripResult)
	success, err := handler.(travel.TravelService).UpdateTrip(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newTravelServiceUpdateTripArgs() interface{} {
	return travel.NewTravelServiceUpdateTripArgs()
}

func newTravelServiceUpdateTripResult() interface{} {
	return travel.NewTravelServiceUpdateTripResult()
}

func createReplanningJobHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*travel.TravelServiceCreateReplanningJobArgs)
	realResult := result.(*travel.TravelServiceCreateReplanningJobResult)
	success, err := handler.(travel.TravelService).CreateReplanningJob(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newTravelServiceCreateReplanningJobArgs() interface{} {
	return travel.NewTravelServiceCreateReplanningJobArgs()
}

func newTravelServiceCreateReplanningJobResult() interface{} {
	return travel.NewTravelServiceCreateReplanningJobResult()
}

func listTripVersionsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*travel.TravelServiceListTripVersionsArgs)
	realResult := result.(*travel.TravelServiceListTripVersionsResult)
	success, err := handler.(travel.TravelService).ListTripVersions(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newTravelServiceListTripVersionsArgs() interface{} {
	return travel.NewTravelServiceListTripVersionsArgs()
}

func newTravelServiceListTripVersionsResult() interface{} {
	return travel.NewTravelServiceListTripVersionsResult()
}

func getTripVersionHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*travel.TravelServiceGetTripVersionArgs)
	realResult := result.(*travel.TravelServiceGetTripVersionResult)
	success, err := handler.(travel.TravelService).GetTripVersion(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newTravelServiceGetTripVersionArgs() interface{} {
	return travel.NewTravelServiceGetTripVersionArgs()
}

func newTravelServiceGetTripVersionResult() interface{} {
	return travel.NewTravelServiceGetTripVersionResult()
}

func getBudgetSummaryHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*travel.TravelServiceGetBudgetSummaryArgs)
	realResult := result.(*travel.TravelServiceGetBudgetSummaryResult)
	success, err := handler.(travel.TravelService).GetBudgetSummary(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newTravelServiceGetBudgetSummaryArgs() interface{} {
	return travel.NewTravelServiceGetBudgetSummaryArgs()
}

func newTravelServiceGetBudgetSummaryResult() interface{} {
	return travel.NewTravelServiceGetBudgetSummaryResult()
}

func healthHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*travel.TravelServiceHealthArgs)
	realResult := result.(*travel.TravelServiceHealthResult)
	success, err := handler.(travel.TravelService).Health(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newTravelServiceHealthArgs() interface{} {
	return travel.NewTravelServiceHealthArgs()
}

func newTravelServiceHealthResult() interface{} {
	return travel.NewTravelServiceHealthResult()
}

func requestRegistrationCodeHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*travel.TravelServiceRequestRegistrationCodeArgs)
	realResult := result.(*travel.TravelServiceRequestRegistrationCodeResult)
	success, err := handler.(travel.TravelService).RequestRegistrationCode(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newTravelServiceRequestRegistrationCodeArgs() interface{} {
	return travel.NewTravelServiceRequestRegistrationCodeArgs()
}

func newTravelServiceRequestRegistrationCodeResult() interface{} {
	return travel.NewTravelServiceRequestRegistrationCodeResult()
}

func legacyLoginHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*travel.TravelServiceLegacyLoginArgs)
	realResult := result.(*travel.TravelServiceLegacyLoginResult)
	success, err := handler.(travel.TravelService).LegacyLogin(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newTravelServiceLegacyLoginArgs() interface{} {
	return travel.NewTravelServiceLegacyLoginArgs()
}

func newTravelServiceLegacyLoginResult() interface{} {
	return travel.NewTravelServiceLegacyLoginResult()
}

func requestEmailBindingCodeHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*travel.TravelServiceRequestEmailBindingCodeArgs)
	realResult := result.(*travel.TravelServiceRequestEmailBindingCodeResult)
	success, err := handler.(travel.TravelService).RequestEmailBindingCode(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newTravelServiceRequestEmailBindingCodeArgs() interface{} {
	return travel.NewTravelServiceRequestEmailBindingCodeArgs()
}

func newTravelServiceRequestEmailBindingCodeResult() interface{} {
	return travel.NewTravelServiceRequestEmailBindingCodeResult()
}

func bindEmailHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*travel.TravelServiceBindEmailArgs)
	realResult := result.(*travel.TravelServiceBindEmailResult)
	success, err := handler.(travel.TravelService).BindEmail(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newTravelServiceBindEmailArgs() interface{} {
	return travel.NewTravelServiceBindEmailArgs()
}

func newTravelServiceBindEmailResult() interface{} {
	return travel.NewTravelServiceBindEmailResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Register(ctx context.Context, req *model.Request) (r *model.Response, err error) {
	var _args travel.TravelServiceRegisterArgs
	_args.Req = req
	var _result travel.TravelServiceRegisterResult
	if err = p.c.Call(ctx, "Register", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Login(ctx context.Context, req *model.Request) (r *model.Response, err error) {
	var _args travel.TravelServiceLoginArgs
	_args.Req = req
	var _result travel.TravelServiceLoginResult
	if err = p.c.Call(ctx, "Login", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Logout(ctx context.Context, req *model.Request) (r *model.Response, err error) {
	var _args travel.TravelServiceLogoutArgs
	_args.Req = req
	var _result travel.TravelServiceLogoutResult
	if err = p.c.Call(ctx, "Logout", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetCurrentUser(ctx context.Context, req *model.Request) (r *model.Response, err error) {
	var _args travel.TravelServiceGetCurrentUserArgs
	_args.Req = req
	var _result travel.TravelServiceGetCurrentUserResult
	if err = p.c.Call(ctx, "GetCurrentUser", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) SearchPlaces(ctx context.Context, req *model.Request) (r *model.Response, err error) {
	var _args travel.TravelServiceSearchPlacesArgs
	_args.Req = req
	var _result travel.TravelServiceSearchPlacesResult
	if err = p.c.Call(ctx, "SearchPlaces", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CreatePlace(ctx context.Context, req *model.Request) (r *model.Response, err error) {
	var _args travel.TravelServiceCreatePlaceArgs
	_args.Req = req
	var _result travel.TravelServiceCreatePlaceResult
	if err = p.c.Call(ctx, "CreatePlace", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpdatePlace(ctx context.Context, req *model.Request) (r *model.Response, err error) {
	var _args travel.TravelServiceUpdatePlaceArgs
	_args.Req = req
	var _result travel.TravelServiceUpdatePlaceResult
	if err = p.c.Call(ctx, "UpdatePlace", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CreatePlanningJob(ctx context.Context, req *model.Request) (r *model.Response, err error) {
	var _args travel.TravelServiceCreatePlanningJobArgs
	_args.Req = req
	var _result travel.TravelServiceCreatePlanningJobResult
	if err = p.c.Call(ctx, "CreatePlanningJob", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetPlanningJob(ctx context.Context, req *model.Request) (r *model.Response, err error) {
	var _args travel.TravelServiceGetPlanningJobArgs
	_args.Req = req
	var _result travel.TravelServiceGetPlanningJobResult
	if err = p.c.Call(ctx, "GetPlanningJob", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) RetryPlanningJob(ctx context.Context, req *model.Request) (r *model.Response, err error) {
	var _args travel.TravelServiceRetryPlanningJobArgs
	_args.Req = req
	var _result travel.TravelServiceRetryPlanningJobResult
	if err = p.c.Call(ctx, "RetryPlanningJob", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListTrips(ctx context.Context, req *model.Request) (r *model.Response, err error) {
	var _args travel.TravelServiceListTripsArgs
	_args.Req = req
	var _result travel.TravelServiceListTripsResult
	if err = p.c.Call(ctx, "ListTrips", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetTrip(ctx context.Context, req *model.Request) (r *model.Response, err error) {
	var _args travel.TravelServiceGetTripArgs
	_args.Req = req
	var _result travel.TravelServiceGetTripResult
	if err = p.c.Call(ctx, "GetTrip", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpdateTrip(ctx context.Context, req *model.Request) (r *model.Response, err error) {
	var _args travel.TravelServiceUpdateTripArgs
	_args.Req = req
	var _result travel.TravelServiceUpdateTripResult
	if err = p.c.Call(ctx, "UpdateTrip", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CreateReplanningJob(ctx context.Context, req *model.Request) (r *model.Response, err error) {
	var _args travel.TravelServiceCreateReplanningJobArgs
	_args.Req = req
	var _result travel.TravelServiceCreateReplanningJobResult
	if err = p.c.Call(ctx, "CreateReplanningJob", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListTripVersions(ctx context.Context, req *model.Request) (r *model.Response, err error) {
	var _args travel.TravelServiceListTripVersionsArgs
	_args.Req = req
	var _result travel.TravelServiceListTripVersionsResult
	if err = p.c.Call(ctx, "ListTripVersions", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetTripVersion(ctx context.Context, req *model.Request) (r *model.Response, err error) {
	var _args travel.TravelServiceGetTripVersionArgs
	_args.Req = req
	var _result travel.TravelServiceGetTripVersionResult
	if err = p.c.Call(ctx, "GetTripVersion", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetBudgetSummary(ctx context.Context, req *model.Request) (r *model.Response, err error) {
	var _args travel.TravelServiceGetBudgetSummaryArgs
	_args.Req = req
	var _result travel.TravelServiceGetBudgetSummaryResult
	if err = p.c.Call(ctx, "GetBudgetSummary", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Health(ctx context.Context, req *model.Request) (r *model.Response, err error) {
	var _args travel.TravelServiceHealthArgs
	_args.Req = req
	var _result travel.TravelServiceHealthResult
	if err = p.c.Call(ctx, "Health", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) RequestRegistrationCode(ctx context.Context, req *model.Request) (r *model.Response, err error) {
	var _args travel.TravelServiceRequestRegistrationCodeArgs
	_args.Req = req
	var _result travel.TravelServiceRequestRegistrationCodeResult
	if err = p.c.Call(ctx, "RequestRegistrationCode", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) LegacyLogin(ctx context.Context, req *model.Request) (r *model.Response, err error) {
	var _args travel.TravelServiceLegacyLoginArgs
	_args.Req = req
	var _result travel.TravelServiceLegacyLoginResult
	if err = p.c.Call(ctx, "LegacyLogin", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) RequestEmailBindingCode(ctx context.Context, req *model.Request) (r *model.Response, err error) {
	var _args travel.TravelServiceRequestEmailBindingCodeArgs
	_args.Req = req
	var _result travel.TravelServiceRequestEmailBindingCodeResult
	if err = p.c.Call(ctx, "RequestEmailBindingCode", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) BindEmail(ctx context.Context, req *model.Request) (r *model.Response, err error) {
	var _args travel.TravelServiceBindEmailArgs
	_args.Req = req
	var _result travel.TravelServiceBindEmailResult
	if err = p.c.Call(ctx, "BindEmail", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
