// Code generated by thriftgo (0.4.5). DO NOT EDIT.

package planner

import (
	"ai-travel/kitex_gen/model"
	"context"
	"fmt"
)

type PlannerService interface {
	GenerateItinerary(ctx context.Context, req *model.PlanningRequest) (r *model.PlanningResult_, err error)

	ReviseItinerary(ctx context.Context, req *model.PlanningRequest) (r *model.PlanningResult_, err error)
}

type PlannerServiceGenerateItineraryArgs struct {
	Req *model.PlanningRequest `thrift:"req,1" frugal:"1,default,model.PlanningRequest" json:"req"`
}

func NewPlannerServiceGenerateItineraryArgs() *PlannerServiceGenerateItineraryArgs {
	return &PlannerServiceGenerateItineraryArgs{}
}

func (p *PlannerServiceGenerateItineraryArgs) InitDefault() {
}

var PlannerServiceGenerateItineraryArgs_Req_DEFAULT *model.PlanningRequest

func (p *PlannerServiceGenerateItineraryArgs) GetReq() (v *model.PlanningRequest) {
	if !p.IsSetReq() {
		return PlannerServiceGenerateItineraryArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *PlannerServiceGenerateItineraryArgs) SetReq(val *model.PlanningRequest) {
	p.Req = val
}

func (p *PlannerServiceGenerateItineraryArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *PlannerServiceGenerateItineraryArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PlannerServiceGenerateItineraryArgs(%+v)", *p)
}

var fieldIDToName_PlannerServiceGenerateItineraryArgs = map[int16]string{
	1: "req",
}

type PlannerServiceGenerateItineraryResult struct {
	Success *model.PlanningResult_ `thrift:"success,0,optional" frugal:"0,optional,model.PlanningResult_" json:"success,omitempty"`
}

func NewPlannerServiceGenerateItineraryResult() *PlannerServiceGenerateItineraryResult {
	return &PlannerServiceGenerateItineraryResult{}
}

func (p *PlannerServiceGenerateItineraryResult) InitDefault() {
}

var PlannerServiceGenerateItineraryResult_Success_DEFAULT *model.PlanningResult_

func (p *PlannerServiceGenerateItineraryResult) GetSuccess() (v *model.PlanningResult_) {
	if !p.IsSetSuccess() {
		return PlannerServiceGenerateItineraryResult_Success_DEFAULT
	}
	return p.Success
}
func (p *PlannerServiceGenerateItineraryResult) SetSuccess(x interface{}) {
	p.Success = x.(*model.PlanningResult_)
}

func (p *PlannerServiceGenerateItineraryResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *PlannerServiceGenerateItineraryResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PlannerServiceGenerateItineraryResult(%+v)", *p)
}

var fieldIDToName_PlannerServiceGenerateItineraryResult = map[int16]string{
	0: "success",
}

type PlannerServiceReviseItineraryArgs struct {
	Req *model.PlanningRequest `thrift:"req,1" frugal:"1,default,model.PlanningRequest" json:"req"`
}

func NewPlannerServiceReviseItineraryArgs() *PlannerServiceReviseItineraryArgs {
	return &PlannerServiceReviseItineraryArgs{}
}

func (p *PlannerServiceReviseItineraryArgs) InitDefault() {
}

var PlannerServiceReviseItineraryArgs_Req_DEFAULT *model.PlanningRequest

func (p *PlannerServiceReviseItineraryArgs) GetReq() (v *model.PlanningRequest) {
	if !p.IsSetReq() {
		return PlannerServiceReviseItineraryArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *PlannerServiceReviseItineraryArgs) SetReq(val *model.PlanningRequest) {
	p.Req = val
}

func (p *PlannerServiceReviseItineraryArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *PlannerServiceReviseItineraryArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PlannerServiceReviseItineraryArgs(%+v)", *p)
}

var fieldIDToName_PlannerServiceReviseItineraryArgs = map[int16]string{
	1: "req",
}

type PlannerServiceReviseItineraryResult struct {
	Success *model.PlanningResult_ `thrift:"success,0,optional" frugal:"0,optional,model.PlanningResult_" json:"success,omitempty"`
}

func NewPlannerServiceReviseItineraryResult() *PlannerServiceReviseItineraryResult {
	return &PlannerServiceReviseItineraryResult{}
}

func (p *PlannerServiceReviseItineraryResult) InitDefault() {
}

var PlannerServiceReviseItineraryResult_Success_DEFAULT *model.PlanningResult_

func (p *PlannerServiceReviseItineraryResult) GetSuccess() (v *model.PlanningResult_) {
	if !p.IsSetSuccess() {
		return PlannerServiceReviseItineraryResult_Success_DEFAULT
	}
	return p.Success
}
func (p *PlannerServiceReviseItineraryResult) SetSuccess(x interface{}) {
	p.Success = x.(*model.PlanningResult_)
}

func (p *PlannerServiceReviseItineraryResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *PlannerServiceReviseItineraryResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PlannerServiceReviseItineraryResult(%+v)", *p)
}

var fieldIDToName_PlannerServiceReviseItineraryResult = map[int16]string{
	0: "success",
}
