// Code generated by Kitex v0.16.3. DO NOT EDIT.

package plannerservice

import (
	model "ai-travel/kitex_gen/model"
	planner "ai-travel/kitex_gen/planner"
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"GenerateItinerary": kitex.NewMethodInfo(
		generateItineraryHandler,
		newPlannerServiceGenerateItineraryArgs,
		newPlannerServiceGenerateItineraryResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ReviseItinerary": kitex.NewMethodInfo(
		reviseItineraryHandler,
		newPlannerServiceReviseItineraryArgs,
		newPlannerServiceReviseItineraryResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	plannerServiceServiceInfo                = NewServiceInfo()
	plannerServiceServiceInfoForClient       = NewServiceInfoForClient()
	plannerServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return plannerServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return plannerServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return plannerServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "PlannerService"
	handlerType := (*planner.PlannerService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "planner",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.16.3",
		Extra:           extra,
	}
	return svcInfo
}

func generateItineraryHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*planner.PlannerServiceGenerateItineraryArgs)
	realResult := result.(*planner.PlannerServiceGenerateItineraryResult)
	success, err := handler.(planner.PlannerService).GenerateItinerary(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newPlannerServiceGenerateItineraryArgs() interface{} {
	return planner.NewPlannerServiceGenerateItineraryArgs()
}

func newPlannerServiceGenerateItineraryResult() interface{} {
	return planner.NewPlannerServiceGenerateItineraryResult()
}

func reviseItineraryHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*planner.PlannerServiceReviseItineraryArgs)
	realResult := result.(*planner.PlannerServiceReviseItineraryResult)
	success, err := handler.(planner.PlannerService).ReviseItinerary(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newPlannerServiceReviseItineraryArgs() interface{} {
	return planner.NewPlannerServiceReviseItineraryArgs()
}

func newPlannerServiceReviseItineraryResult() interface{} {
	return planner.NewPlannerServiceReviseItineraryResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) GenerateItinerary(ctx context.Context, req *model.PlanningRequest) (r *model.PlanningResult_, err error) {
	var _args planner.PlannerServiceGenerateItineraryArgs
	_args.Req = req
	var _result planner.PlannerServiceGenerateItineraryResult
	if err = p.c.Call(ctx, "GenerateItinerary", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ReviseItinerary(ctx context.Context, req *model.PlanningRequest) (r *model.PlanningResult_, err error) {
	var _args planner.PlannerServiceReviseItineraryArgs
	_args.Req = req
	var _result planner.PlannerServiceReviseItineraryResult
	if err = p.c.Call(ctx, "ReviseItinerary", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
