// Code generated by thriftgo (0.4.5). DO NOT EDIT.

package travel

import (
	"ai-travel/kitex_gen/model"
	"context"
	"fmt"
)

type TravelService interface {
	Register(ctx context.Context, req *model.Request) (r *model.Response, err error)

	Login(ctx context.Context, req *model.Request) (r *model.Response, err error)

	Logout(ctx context.Context, req *model.Request) (r *model.Response, err error)

	GetCurrentUser(ctx context.Context, req *model.Request) (r *model.Response, err error)

	SearchPlaces(ctx context.Context, req *model.Request) (r *model.Response, err error)

	CreatePlace(ctx context.Context, req *model.Request) (r *model.Response, err error)

	UpdatePlace(ctx context.Context, req *model.Request) (r *model.Response, err error)

	CreatePlanningJob(ctx context.Context, req *model.Request) (r *model.Response, err error)

	GetPlanningJob(ctx context.Context, req *model.Request) (r *model.Response, err error)

	RetryPlanningJob(ctx context.Context, req *model.Request) (r *model.Response, err error)

	ListTrips(ctx context.Context, req *model.Request) (r *model.Response, err error)

	GetTrip(ctx context.Context, req *model.Request) (r *model.Response, err error)

	UpdateTrip(ctx context.Context, req *model.Request) (r *model.Response, err error)

	CreateReplanningJob(ctx context.Context, req *model.Request) (r *model.Response, err error)

	ListTripVersions(ctx context.Context, req *model.Request) (r *model.Response, err error)

	GetTripVersion(ctx context.Context, req *model.Request) (r *model.Response, err error)

	GetBudgetSummary(ctx context.Context, req *model.Request) (r *model.Response, err error)

	Health(ctx context.Context, req *model.Request) (r *model.Response, err error)

	RequestRegistrationCode(ctx context.Context, req *model.Request) (r *model.Response, err error)

	LegacyLogin(ctx context.Context, req *model.Request) (r *model.Response, err error)

	RequestEmailBindingCode(ctx context.Context, req *model.Request) (r *model.Response, err error)

	BindEmail(ctx context.Context, req *model.Request) (r *model.Response, err error)
}

type TravelServiceRegisterArgs struct {
	Req *model.Request `thrift:"req,1" frugal:"1,default,model.Request" json:"req"`
}

func NewTravelServiceRegisterArgs() *TravelServiceRegisterArgs {
	return &TravelServiceRegisterArgs{}
}

func (p *TravelServiceRegisterArgs) InitDefault() {
}

var TravelServiceRegisterArgs_Req_DEFAULT *model.Request

func (p *TravelServiceRegisterArgs) GetReq() (v *model.Request) {
	if !p.IsSetReq() {
		return TravelServiceRegisterArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *TravelServiceRegisterArgs) SetReq(val *model.Request) {
	p.Req = val
}

func (p *TravelServiceRegisterArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *TravelServiceRegisterArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TravelServiceRegisterArgs(%+v)", *p)
}

var fieldIDToName_TravelServiceRegisterArgs = map[int16]string{
	1: "req",
}

type TravelServiceRegisterResult struct {
	Success *model.Response `thrift:"success,0,optional" frugal:"0,optional,model.Response" json:"success,omitempty"`
}

func NewTravelServiceRegisterResult() *TravelServiceRegisterResult {
	return &TravelServiceRegisterResult{}
}

func (p *TravelServiceRegisterResult) InitDefault() {
}

var TravelServiceRegisterResult_Success_DEFAULT *model.Response

func (p *TravelServiceRegisterResult) GetSuccess() (v *model.Response) {
	if !p.IsSetSuccess() {
		return TravelServiceRegisterResult_Success_DEFAULT
	}
	return p.Success
}
func (p *TravelServiceRegisterResult) SetSuccess(x interface{}) {
	p.Success = x.(*model.Response)
}

func (p *TravelServiceRegisterResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *TravelServiceRegisterResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TravelServiceRegisterResult(%+v)", *p)
}

var fieldIDToName_TravelServiceRegisterResult = map[int16]string{
	0: "success",
}

type TravelServiceLoginArgs struct {
	Req *model.Request `thrift:"req,1" frugal:"1,default,model.Request" json:"req"`
}

func NewTravelServiceLoginArgs() *TravelServiceLoginArgs {
	return &TravelServiceLoginArgs{}
}

func (p *TravelServiceLoginArgs) InitDefault() {
}

var TravelServiceLoginArgs_Req_DEFAULT *model.Request

func (p *TravelServiceLoginArgs) GetReq() (v *model.Request) {
	if !p.IsSetReq() {
		return TravelServiceLoginArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *TravelServiceLoginArgs) SetReq(val *model.Request) {
	p.Req = val
}

func (p *TravelServiceLoginArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *TravelServiceLoginArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TravelServiceLoginArgs(%+v)", *p)
}

var fieldIDToName_TravelServiceLoginArgs = map[int16]string{
	1: "req",
}

type TravelServiceLoginResult struct {
	Success *model.Response `thrift:"success,0,optional" frugal:"0,optional,model.Response" json:"success,omitempty"`
}

func NewTravelServiceLoginResult() *TravelServiceLoginResult {
	return &TravelServiceLoginResult{}
}

func (p *TravelServiceLoginResult) InitDefault() {
}

var TravelServiceLoginResult_Success_DEFAULT *model.Response

func (p *TravelServiceLoginResult) GetSuccess() (v *model.Response) {
	if !p.IsSetSuccess() {
		return TravelServiceLoginResult_Success_DEFAULT
	}
	return p.Success
}
func (p *TravelServiceLoginResult) SetSuccess(x interface{}) {
	p.Success = x.(*model.Response)
}

func (p *TravelServiceLoginResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *TravelServiceLoginResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TravelServiceLoginResult(%+v)", *p)
}

var fieldIDToName_TravelServiceLoginResult = map[int16]string{
	0: "success",
}

type TravelServiceLogoutArgs struct {
	Req *model.Request `thrift:"req,1" frugal:"1,default,model.Request" json:"req"`
}

func NewTravelServiceLogoutArgs() *TravelServiceLogoutArgs {
	return &TravelServiceLogoutArgs{}
}

func (p *TravelServiceLogoutArgs) InitDefault() {
}

var TravelServiceLogoutArgs_Req_DEFAULT *model.Request

func (p *TravelServiceLogoutArgs) GetReq() (v *model.Request) {
	if !p.IsSetReq() {
		return TravelServiceLogoutArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *TravelServiceLogoutArgs) SetReq(val *model.Request) {
	p.Req = val
}

func (p *TravelServiceLogoutArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *TravelServiceLogoutArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TravelServiceLogoutArgs(%+v)", *p)
}

var fieldIDToName_TravelServiceLogoutArgs = map[int16]string{
	1: "req",
}

type TravelServiceLogoutResult struct {
	Success *model.Response `thrift:"success,0,optional" frugal:"0,optional,model.Response" json:"success,omitempty"`
}

func NewTravelServiceLogoutResult() *TravelServiceLogoutResult {
	return &TravelServiceLogoutResult{}
}

func (p *TravelServiceLogoutResult) InitDefault() {
}

var TravelServiceLogoutResult_Success_DEFAULT *model.Response

func (p *TravelServiceLogoutResult) GetSuccess() (v *model.Response) {
	if !p.IsSetSuccess() {
		return TravelServiceLogoutResult_Success_DEFAULT
	}
	return p.Success
}
func (p *TravelServiceLogoutResult) SetSuccess(x interface{}) {
	p.Success = x.(*model.Response)
}

func (p *TravelServiceLogoutResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *TravelServiceLogoutResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TravelServiceLogoutResult(%+v)", *p)
}

var fieldIDToName_TravelServiceLogoutResult = map[int16]string{
	0: "success",
}

type TravelServiceGetCurrentUserArgs struct {
	Req *model.Request `thrift:"req,1" frugal:"1,default,model.Request" json:"req"`
}

func NewTravelServiceGetCurrentUserArgs() *TravelServiceGetCurrentUserArgs {
	return &TravelServiceGetCurrentUserArgs{}
}

func (p *TravelServiceGetCurrentUserArgs) InitDefault() {
}

var TravelServiceGetCurrentUserArgs_Req_DEFAULT *model.Request

func (p *TravelServiceGetCurrentUserArgs) GetReq() (v *model.Request) {
	if !p.IsSetReq() {
		return TravelServiceGetCurrentUserArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *TravelServiceGetCurrentUserArgs) SetReq(val *model.Request) {
	p.Req = val
}

func (p *TravelServiceGetCurrentUserArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *TravelServiceGetCurrentUserArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TravelServiceGetCurrentUserArgs(%+v)", *p)
}

var fieldIDToName_TravelServiceGetCurrentUserArgs = map[int16]string{
	1: "req",
}

type TravelServiceGetCurrentUserResult struct {
	Success *model.Response `thrift:"success,0,optional" frugal:"0,optional,model.Response" json:"success,omitempty"`
}

func NewTravelServiceGetCurrentUserResult() *TravelServiceGetCurrentUserResult {
	return &TravelServiceGetCurrentUserResult{}
}

func (p *TravelServiceGetCurrentUserResult) InitDefault() {
}

var TravelServiceGetCurrentUserResult_Success_DEFAULT *model.Response

func (p *TravelServiceGetCurrentUserResult) GetSuccess() (v *model.Response) {
	if !p.IsSetSuccess() {
		return TravelServiceGetCurrentUserResult_Success_DEFAULT
	}
	return p.Success
}
func (p *TravelServiceGetCurrentUserResult) SetSuccess(x interface{}) {
	p.Success = x.(*model.Response)
}

func (p *TravelServiceGetCurrentUserResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *TravelServiceGetCurrentUserResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TravelServiceGetCurrentUserResult(%+v)", *p)
}

var fieldIDToName_TravelServiceGetCurrentUserResult = map[int16]string{
	0: "success",
}

type TravelServiceSearchPlacesArgs struct {
	Req *model.Request `thrift:"req,1" frugal:"1,default,model.Request" json:"req"`
}

func NewTravelServiceSearchPlacesArgs() *TravelServiceSearchPlacesArgs {
	return &TravelServiceSearchPlacesArgs{}
}

func (p *TravelServiceSearchPlacesArgs) InitDefault() {
}

var TravelServiceSearchPlacesArgs_Req_DEFAULT *model.Request

func (p *TravelServiceSearchPlacesArgs) GetReq() (v *model.Request) {
	if !p.IsSetReq() {
		return TravelServiceSearchPlacesArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *TravelServiceSearchPlacesArgs) SetReq(val *model.Request) {
	p.Req = val
}

func (p *TravelServiceSearchPlacesArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *TravelServiceSearchPlacesArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TravelServiceSearchPlacesArgs(%+v)", *p)
}

var fieldIDToName_TravelServiceSearchPlacesArgs = map[int16]string{
	1: "req",
}

type TravelServiceSearchPlacesResult struct {
	Success *model.Response `thrift:"success,0,optional" frugal:"0,optional,model.Response" json:"success,omitempty"`
}

func NewTravelServiceSearchPlacesResult() *TravelServiceSearchPlacesResult {
	return &TravelServiceSearchPlacesResult{}
}

func (p *TravelServiceSearchPlacesResult) InitDefault() {
}

var TravelServiceSearchPlacesResult_Success_DEFAULT *model.Response

func (p *TravelServiceSearchPlacesResult) GetSuccess() (v *model.Response) {
	if !p.IsSetSuccess() {
		return TravelServiceSearchPlacesResult_Success_DEFAULT
	}
	return p.Success
}
func (p *TravelServiceSearchPlacesResult) SetSuccess(x interface{}) {
	p.Success = x.(*model.Response)
}

func (p *TravelServiceSearchPlacesResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *TravelServiceSearchPlacesResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TravelServiceSearchPlacesResult(%+v)", *p)
}

var fieldIDToName_TravelServiceSearchPlacesResult = map[int16]string{
	0: "success",
}

type TravelServiceCreatePlaceArgs struct {
	Req *model.Request `thrift:"req,1" frugal:"1,default,model.Request" json:"req"`
}

func NewTravelServiceCreatePlaceArgs() *TravelServiceCreatePlaceArgs {
	return &TravelServiceCreatePlaceArgs{}
}

func (p *TravelServiceCreatePlaceArgs) InitDefault() {
}

var TravelServiceCreatePlaceArgs_Req_DEFAULT *model.Request

func (p *TravelServiceCreatePlaceArgs) GetReq() (v *model.Request) {
	if !p.IsSetReq() {
		return TravelServiceCreatePlaceArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *TravelServiceCreatePlaceArgs) SetReq(val *model.Request) {
	p.Req = val
}

func (p *TravelServiceCreatePlaceArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *TravelServiceCreatePlaceArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TravelServiceCreatePlaceArgs(%+v)", *p)
}

var fieldIDToName_TravelServiceCreatePlaceArgs = map[int16]string{
	1: "req",
}

type TravelServiceCreatePlaceResult struct {
	Success *model.Response `thrift:"success,0,optional" frugal:"0,optional,model.Response" json:"success,omitempty"`
}

func NewTravelServiceCreatePlaceResult() *TravelServiceCreatePlaceResult {
	return &TravelServiceCreatePlaceResult{}
}

func (p *TravelServiceCreatePlaceResult) InitDefault() {
}

var TravelServiceCreatePlaceResult_Success_DEFAULT *model.Response

func (p *TravelServiceCreatePlaceResult) GetSuccess() (v *model.Response) {
	if !p.IsSetSuccess() {
		return TravelServiceCreatePlaceResult_Success_DEFAULT
	}
	return p.Success
}
func (p *TravelServiceCreatePlaceResult) SetSuccess(x interface{}) {
	p.Success = x.(*model.Response)
}

func (p *TravelServiceCreatePlaceResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *TravelServiceCreatePlaceResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TravelServiceCreatePlaceResult(%+v)", *p)
}

var fieldIDToName_TravelServiceCreatePlaceResult = map[int16]string{
	0: "success",
}

type TravelServiceUpdatePlaceArgs struct {
	Req *model.Request `thrift:"req,1" frugal:"1,default,model.Request" json:"req"`
}

func NewTravelServiceUpdatePlaceArgs() *TravelServiceUpdatePlaceArgs {
	return &TravelServiceUpdatePlaceArgs{}
}

func (p *TravelServiceUpdatePlaceArgs) InitDefault() {
}

var TravelServiceUpdatePlaceArgs_Req_DEFAULT *model.Request

func (p *TravelServiceUpdatePlaceArgs) GetReq() (v *model.Request) {
	if !p.IsSetReq() {
		return TravelServiceUpdatePlaceArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *TravelServiceUpdatePlaceArgs) SetReq(val *model.Request) {
	p.Req = val
}

func (p *TravelServiceUpdatePlaceArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *TravelServiceUpdatePlaceArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TravelServiceUpdatePlaceArgs(%+v)", *p)
}

var fieldIDToName_TravelServiceUpdatePlaceArgs = map[int16]string{
	1: "req",
}

type TravelServiceUpdatePlaceResult struct {
	Success *model.Response `thrift:"success,0,optional" frugal:"0,optional,model.Response" json:"success,omitempty"`
}

func NewTravelServiceUpdatePlaceResult() *TravelServiceUpdatePlaceResult {
	return &TravelServiceUpdatePlaceResult{}
}

func (p *TravelServiceUpdatePlaceResult) InitDefault() {
}

var TravelServiceUpdatePlaceResult_Success_DEFAULT *model.Response

func (p *TravelServiceUpdatePlaceResult) GetSuccess() (v *model.Response) {
	if !p.IsSetSuccess() {
		return TravelServiceUpdatePlaceResult_Success_DEFAULT
	}
	return p.Success
}
func (p *TravelServiceUpdatePlaceResult) SetSuccess(x interface{}) {
	p.Success = x.(*model.Response)
}

func (p *TravelServiceUpdatePlaceResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *TravelServiceUpdatePlaceResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TravelServiceUpdatePlaceResult(%+v)", *p)
}

var fieldIDToName_TravelServiceUpdatePlaceResult = map[int16]string{
	0: "success",
}

type TravelServiceCreatePlanningJobArgs struct {
	Req *model.Request `thrift:"req,1" frugal:"1,default,model.Request" json:"req"`
}

func NewTravelServiceCreatePlanningJobArgs() *TravelServiceCreatePlanningJobArgs {
	return &TravelServiceCreatePlanningJobArgs{}
}

func (p *TravelServiceCreatePlanningJobArgs) InitDefault() {
}

var TravelServiceCreatePlanningJobArgs_Req_DEFAULT *model.Request

func (p *TravelServiceCreatePlanningJobArgs) GetReq() (v *model.Request) {
	if !p.IsSetReq() {
		return TravelServiceCreatePlanningJobArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *TravelServiceCreatePlanningJobArgs) SetReq(val *model.Request) {
	p.Req = val
}

func (p *TravelServiceCreatePlanningJobArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *TravelServiceCreatePlanningJobArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TravelServiceCreatePlanningJobArgs(%+v)", *p)
}

var fieldIDToName_TravelServiceCreatePlanningJobArgs = map[int16]string{
	1: "req",
}

type TravelServiceCreatePlanningJobResult struct {
	Success *model.Response `thrift:"success,0,optional" frugal:"0,optional,model.Response" json:"success,omitempty"`
}

func NewTravelServiceCreatePlanningJobResult() *TravelServiceCreatePlanningJobResult {
	return &TravelServiceCreatePlanningJobResult{}
}

func (p *TravelServiceCreatePlanningJobResult) InitDefault() {
}

var TravelServiceCreatePlanningJobResult_Success_DEFAULT *model.Response

func (p *TravelServiceCreatePlanningJobResult) GetSuccess() (v *model.Response) {
	if !p.IsSetSuccess() {
		return TravelServiceCreatePlanningJobResult_Success_DEFAULT
	}
	return p.Success
}
func (p *TravelServiceCreatePlanningJobResult) SetSuccess(x interface{}) {
	p.Success = x.(*model.Response)
}

func (p *TravelServiceCreatePlanningJobResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *TravelServiceCreatePlanningJobResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TravelServiceCreatePlanningJobResult(%+v)", *p)
}

var fieldIDToName_TravelServiceCreatePlanningJobResult = map[int16]string{
	0: "success",
}

type TravelServiceGetPlanningJobArgs struct {
	Req *model.Request `thrift:"req,1" frugal:"1,default,model.Request" json:"req"`
}

func NewTravelServiceGetPlanningJobArgs() *TravelServiceGetPlanningJobArgs {
	return &TravelServiceGetPlanningJobArgs{}
}

func (p *TravelServiceGetPlanningJobArgs) InitDefault() {
}

var TravelServiceGetPlanningJobArgs_Req_DEFAULT *model.Request

func (p *TravelServiceGetPlanningJobArgs) GetReq() (v *model.Request) {
	if !p.IsSetReq() {
		return TravelServiceGetPlanningJobArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *TravelServiceGetPlanningJobArgs) SetReq(val *model.Request) {
	p.Req = val
}

func (p *TravelServiceGetPlanningJobArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *TravelServiceGetPlanningJobArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TravelServiceGetPlanningJobArgs(%+v)", *p)
}

var fieldIDToName_TravelServiceGetPlanningJobArgs = map[int16]string{
	1: "req",
}

type TravelServiceGetPlanningJobResult struct {
	Success *model.Response `thrift:"success,0,optional" frugal:"0,optional,model.Response" json:"success,omitempty"`
}

func NewTravelServiceGetPlanningJobResult() *TravelServiceGetPlanningJobResult {
	return &TravelServiceGetPlanningJobResult{}
}

func (p *TravelServiceGetPlanningJobResult) InitDefault() {
}

var TravelServiceGetPlanningJobResult_Success_DEFAULT *model.Response

func (p *TravelServiceGetPlanningJobResult) GetSuccess() (v *model.Response) {
	if !p.IsSetSuccess() {
		return TravelServiceGetPlanningJobResult_Success_DEFAULT
	}
	return p.Success
}
func (p *TravelServiceGetPlanningJobResult) SetSuccess(x interface{}) {
	p.Success = x.(*model.Response)
}

func (p *TravelServiceGetPlanningJobResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *TravelServiceGetPlanningJobResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TravelServiceGetPlanningJobResult(%+v)", *p)
}

var fieldIDToName_TravelServiceGetPlanningJobResult = map[int16]string{
	0: "success",
}

type TravelServiceRetryPlanningJobArgs struct {
	Req *model.Request `thrift:"req,1" frugal:"1,default,model.Request" json:"req"`
}

func NewTravelServiceRetryPlanningJobArgs() *TravelServiceRetryPlanningJobArgs {
	return &TravelServiceRetryPlanningJobArgs{}
}

func (p *TravelServiceRetryPlanningJobArgs) InitDefault() {
}

var TravelServiceRetryPlanningJobArgs_Req_DEFAULT *model.Request

func (p *TravelServiceRetryPlanningJobArgs) GetReq() (v *model.Request) {
	if !p.IsSetReq() {
		return TravelServiceRetryPlanningJobArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *TravelServiceRetryPlanningJobArgs) SetReq(val *model.Request) {
	p.Req = val
}

func (p *TravelServiceRetryPlanningJobArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *TravelServiceRetryPlanningJobArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TravelServiceRetryPlanningJobArgs(%+v)", *p)
}

var fieldIDToName_TravelServiceRetryPlanningJobArgs = map[int16]string{
	1: "req",
}

type TravelServiceRetryPlanningJobResult struct {
	Success *model.Response `thrift:"success,0,optional" frugal:"0,optional,model.Response" json:"success,omitempty"`
}

func NewTravelServiceRetryPlanningJobResult() *TravelServiceRetryPlanningJobResult {
	return &TravelServiceRetryPlanningJobResult{}
}

func (p *TravelServiceRetryPlanningJobResult) InitDefault() {
}

var TravelServiceRetryPlanningJobResult_Success_DEFAULT *model.Response

func (p *TravelServiceRetryPlanningJobResult) GetSuccess() (v *model.Response) {
	if !p.IsSetSuccess() {
		return TravelServiceRetryPlanningJobResult_Success_DEFAULT
	}
	return p.Success
}
func (p *TravelServiceRetryPlanningJobResult) SetSuccess(x interface{}) {
	p.Success = x.(*model.Response)
}

func (p *TravelServiceRetryPlanningJobResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *TravelServiceRetryPlanningJobResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TravelServiceRetryPlanningJobResult(%+v)", *p)
}

var fieldIDToName_TravelServiceRetryPlanningJobResult = map[int16]string{
	0: "success",
}

type TravelServiceListTripsArgs struct {
	Req *model.Request `thrift:"req,1" frugal:"1,default,model.Request" json:"req"`
}

func NewTravelServiceListTripsArgs() *TravelServiceListTripsArgs {
	return &TravelServiceListTripsArgs{}
}

func (p *TravelServiceListTripsArgs) InitDefault() {
}

var TravelServiceListTripsArgs_Req_DEFAULT *model.Request

func (p *TravelServiceListTripsArgs) GetReq() (v *model.Request) {
	if !p.IsSetReq() {
		return TravelServiceListTripsArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *TravelServiceListTripsArgs) SetReq(val *model.Request) {
	p.Req = val
}

func (p *TravelServiceListTripsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *TravelServiceListTripsArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TravelServiceListTripsArgs(%+v)", *p)
}

var fieldIDToName_TravelServiceListTripsArgs = map[int16]string{
	1: "req",
}

type TravelServiceListTripsResult struct {
	Success *model.Response `thrift:"success,0,optional" frugal:"0,optional,model.Response" json:"success,omitempty"`
}

func NewTravelServiceListTripsResult() *TravelServiceListTripsResult {
	return &TravelServiceListTripsResult{}
}

func (p *TravelServiceListTripsResult) InitDefault() {
}

var TravelServiceListTripsResult_Success_DEFAULT *model.Response

func (p *TravelServiceListTripsResult) GetSuccess() (v *model.Response) {
	if !p.IsSetSuccess() {
		return TravelServiceListTripsResult_Success_DEFAULT
	}
	return p.Success
}
func (p *TravelServiceListTripsResult) SetSuccess(x interface{}) {
	p.Success = x.(*model.Response)
}

func (p *TravelServiceListTripsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *TravelServiceListTripsResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TravelServiceListTripsResult(%+v)", *p)
}

var fieldIDToName_TravelServiceListTripsResult = map[int16]string{
	0: "success",
}

type TravelServiceGetTripArgs struct {
	Req *model.Request `thrift:"req,1" frugal:"1,default,model.Request" json:"req"`
}

func NewTravelServiceGetTripArgs() *TravelServiceGetTripArgs {
	return &TravelServiceGetTripArgs{}
}

func (p *TravelServiceGetTripArgs) InitDefault() {
}

var TravelServiceGetTripArgs_Req_DEFAULT *model.Request

func (p *TravelServiceGetTripArgs) GetReq() (v *model.Request) {
	if !p.IsSetReq() {
		return TravelServiceGetTripArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *TravelServiceGetTripArgs) SetReq(val *model.Request) {
	p.Req = val
}

func (p *TravelServiceGetTripArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *TravelServiceGetTripArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TravelServiceGetTripArgs(%+v)", *p)
}

var fieldIDToName_TravelServiceGetTripArgs = map[int16]string{
	1: "req",
}

type TravelServiceGetTripResult struct {
	Success *model.Response `thrift:"success,0,optional" frugal:"0,optional,model.Response" json:"success,omitempty"`
}

func NewTravelServiceGetTripResult() *TravelServiceGetTripResult {
	return &TravelServiceGetTripResult{}
}

func (p *TravelServiceGetTripResult) InitDefault() {
}

var TravelServiceGetTripResult_Success_DEFAULT *model.Response

func (p *TravelServiceGetTripResult) GetSuccess() (v *model.Response) {
	if !p.IsSetSuccess() {
		return TravelServiceGetTripResult_Success_DEFAULT
	}
	return p.Success
}
func (p *TravelServiceGetTripResult) SetSuccess(x interface{}) {
	p.Success = x.(*model.Response)
}

func (p *TravelServiceGetTripResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *TravelServiceGetTripResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TravelServiceGetTripResult(%+v)", *p)
}

var fieldIDToName_TravelServiceGetTripResult = map[int16]string{
	0: "success",
}

type TravelServiceUpdateTripArgs struct {
	Req *model.Request `thrift:"req,1" frugal:"1,default,model.Request" json:"req"`
}

func NewTravelServiceUpdateTripArgs() *TravelServiceUpdateTripArgs {
	return &TravelServiceUpdateTripArgs{}
}

func (p *TravelServiceUpdateTripArgs) InitDefault() {
}

var TravelServiceUpdateTripArgs_Req_DEFAULT *model.Request

func (p *TravelServiceUpdateTripArgs) GetReq() (v *model.Request) {
	if !p.IsSetReq() {
		return TravelServiceUpdateTripArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *TravelServiceUpdateTripArgs) SetReq(val *model.Request) {
	p.Req = val
}

func (p *TravelServiceUpdateTripArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *TravelServiceUpdateTripArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TravelServiceUpdateTripArgs(%+v)", *p)
}

var fieldIDToName_TravelServiceUpdateTripArgs = map[int16]string{
	1: "req",
}

type TravelServiceUpdateTripResult struct {
	Success *model.Response `thrift:"success,0,optional" frugal:"0,optional,model.Response" json:"success,omitempty"`
}

func NewTravelServiceUpdateTripResult() *TravelServiceUpdateTripResult {
	return &TravelServiceUpdateTripResult{}
}

func (p *TravelServiceUpdateTripResult) InitDefault() {
}

var TravelServiceUpdateTripResult_Success_DEFAULT *model.Response

func (p *TravelServiceUpdateTripResult) GetSuccess() (v *model.Response) {
	if !p.IsSetSuccess() {
		return TravelServiceUpdateTripResult_Success_DEFAULT
	}
	return p.Success
}
func (p *TravelServiceUpdateTripResult) SetSuccess(x interface{}) {
	p.Success = x.(*model.Response)
}

func (p *TravelServiceUpdateTripResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *TravelServiceUpdateTripResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TravelServiceUpdateTripResult(%+v)", *p)
}

var fieldIDToName_TravelServiceUpdateTripResult = map[int16]string{
	0: "success",
}

type TravelServiceCreateReplanningJobArgs struct {
	Req *model.Request `thrift:"req,1" frugal:"1,default,model.Request" json:"req"`
}

func NewTravelServiceCreateReplanningJobArgs() *TravelServiceCreateReplanningJobArgs {
	return &TravelServiceCreateReplanningJobArgs{}
}

func (p *TravelServiceCreateReplanningJobArgs) InitDefault() {
}

var TravelServiceCreateReplanningJobArgs_Req_DEFAULT *model.Request

func (p *TravelServiceCreateReplanningJobArgs) GetReq() (v *model.Request) {
	if !p.IsSetReq() {
		return TravelServiceCreateReplanningJobArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *TravelServiceCreateReplanningJobArgs) SetReq(val *model.Request) {
	p.Req = val
}

func (p *TravelServiceCreateReplanningJobArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *TravelServiceCreateReplanningJobArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TravelServiceCreateReplanningJobArgs(%+v)", *p)
}

var fieldIDToName_TravelServiceCreateReplanningJobArgs = map[int16]string{
	1: "req",
}

type TravelServiceCreateReplanningJobResult struct {
	Success *model.Response `thrift:"success,0,optional" frugal:"0,optional,model.Response" json:"success,omitempty"`
}

func NewTravelServiceCreateReplanningJobResult() *TravelServiceCreateReplanningJobResult {
	return &TravelServiceCreateReplanningJobResult{}
}

func (p *TravelServiceCreateReplanningJobResult) InitDefault() {
}

var TravelServiceCreateReplanningJobResult_Success_DEFAULT *model.Response

func (p *TravelServiceCreateReplanningJobResult) GetSuccess() (v *model.Response) {
	if !p.IsSetSuccess() {
		return TravelServiceCreateReplanningJobResult_Success_DEFAULT
	}
	return p.Success
}
func (p *TravelServiceCreateReplanningJobResult) SetSuccess(x interface{}) {
	p.Success = x.(*model.Response)
}

func (p *TravelServiceCreateReplanningJobResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *TravelServiceCreateReplanningJobResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TravelServiceCreateReplanningJobResult(%+v)", *p)
}

var fieldIDToName_TravelServiceCreateReplanningJobResult = map[int16]string{
	0: "success",
}

type TravelServiceListTripVersionsArgs struct {
	Req *model.Request `thrift:"req,1" frugal:"1,default,model.Request" json:"req"`
}

func NewTravelServiceListTripVersionsArgs() *TravelServiceListTripVersionsArgs {
	return &TravelServiceListTripVersionsArgs{}
}

func (p *TravelServiceListTripVersionsArgs) InitDefault() {
}

var TravelServiceListTripVersionsArgs_Req_DEFAULT *model.Request

func (p *TravelServiceListTripVersionsArgs) GetReq() (v *model.Request) {
	if !p.IsSetReq() {
		return TravelServiceListTripVersionsArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *TravelServiceListTripVersionsArgs) SetReq(val *model.Request) {
	p.Req = val
}

func (p *TravelServiceListTripVersionsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *TravelServiceListTripVersionsArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TravelServiceListTripVersionsArgs(%+v)", *p)
}

var fieldIDToName_TravelServiceListTripVersionsArgs = map[int16]string{
	1: "req",
}

type TravelServiceListTripVersionsResult struct {
	Success *model.Response `thrift:"success,0,optional" frugal:"0,optional,model.Response" json:"success,omitempty"`
}

func NewTravelServiceListTripVersionsResult() *TravelServiceListTripVersionsResult {
	return &TravelServiceListTripVersionsResult{}
}

func (p *TravelServiceListTripVersionsResult) InitDefault() {
}

var TravelServiceListTripVersionsResult_Success_DEFAULT *model.Response

func (p *TravelServiceListTripVersionsResult) GetSuccess() (v *model.Response) {
	if !p.IsSetSuccess() {
		return TravelServiceListTripVersionsResult_Success_DEFAULT
	}
	return p.Success
}
func (p *TravelServiceListTripVersionsResult) SetSuccess(x interface{}) {
	p.Success = x.(*model.Response)
}

func (p *TravelServiceListTripVersionsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *TravelServiceListTripVersionsResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TravelServiceListTripVersionsResult(%+v)", *p)
}

var fieldIDToName_TravelServiceListTripVersionsResult = map[int16]string{
	0: "success",
}

type TravelServiceGetTripVersionArgs struct {
	Req *model.Request `thrift:"req,1" frugal:"1,default,model.Request" json:"req"`
}

func NewTravelServiceGetTripVersionArgs() *TravelServiceGetTripVersionArgs {
	return &TravelServiceGetTripVersionArgs{}
}

func (p *TravelServiceGetTripVersionArgs) InitDefault() {
}

var TravelServiceGetTripVersionArgs_Req_DEFAULT *model.Request

func (p *TravelServiceGetTripVersionArgs) GetReq() (v *model.Request) {
	if !p.IsSetReq() {
		return TravelServiceGetTripVersionArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *TravelServiceGetTripVersionArgs) SetReq(val *model.Request) {
	p.Req = val
}

func (p *TravelServiceGetTripVersionArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *TravelServiceGetTripVersionArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TravelServiceGetTripVersionArgs(%+v)", *p)
}

var fieldIDToName_TravelServiceGetTripVersionArgs = map[int16]string{
	1: "req",
}

type TravelServiceGetTripVersionResult struct {
	Success *model.Response `thrift:"success,0,optional" frugal:"0,optional,model.Response" json:"success,omitempty"`
}

func NewTravelServiceGetTripVersionResult() *TravelServiceGetTripVersionResult {
	return &TravelServiceGetTripVersionResult{}
}

func (p *TravelServiceGetTripVersionResult) InitDefault() {
}

var TravelServiceGetTripVersionResult_Success_DEFAULT *model.Response

func (p *TravelServiceGetTripVersionResult) GetSuccess() (v *model.Response) {
	if !p.IsSetSuccess() {
		return TravelServiceGetTripVersionResult_Success_DEFAULT
	}
	return p.Success
}
func (p *TravelServiceGetTripVersionResult) SetSuccess(x interface{}) {
	p.Success = x.(*model.Response)
}

func (p *TravelServiceGetTripVersionResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *TravelServiceGetTripVersionResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TravelServiceGetTripVersionResult(%+v)", *p)
}

var fieldIDToName_TravelServiceGetTripVersionResult = map[int16]string{
	0: "success",
}

type TravelServiceGetBudgetSummaryArgs struct {
	Req *model.Request `thrift:"req,1" frugal:"1,default,model.Request" json:"req"`
}

func NewTravelServiceGetBudgetSummaryArgs() *TravelServiceGetBudgetSummaryArgs {
	return &TravelServiceGetBudgetSummaryArgs{}
}

func (p *TravelServiceGetBudgetSummaryArgs) InitDefault() {
}

var TravelServiceGetBudgetSummaryArgs_Req_DEFAULT *model.Request

func (p *TravelServiceGetBudgetSummaryArgs) GetReq() (v *model.Request) {
	if !p.IsSetReq() {
		return TravelServiceGetBudgetSummaryArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *TravelServiceGetBudgetSummaryArgs) SetReq(val *model.Request) {
	p.Req = val
}

func (p *TravelServiceGetBudgetSummaryArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *TravelServiceGetBudgetSummaryArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TravelServiceGetBudgetSummaryArgs(%+v)", *p)
}

var fieldIDToName_TravelServiceGetBudgetSummaryArgs = map[int16]string{
	1: "req",
}

type TravelServiceGetBudgetSummaryResult struct {
	Success *model.Response `thrift:"success,0,optional" frugal:"0,optional,model.Response" json:"success,omitempty"`
}

func NewTravelServiceGetBudgetSummaryResult() *TravelServiceGetBudgetSummaryResult {
	return &TravelServiceGetBudgetSummaryResult{}
}

func (p *TravelServiceGetBudgetSummaryResult) InitDefault() {
}

var TravelServiceGetBudgetSummaryResult_Success_DEFAULT *model.Response

func (p *TravelServiceGetBudgetSummaryResult) GetSuccess() (v *model.Response) {
	if !p.IsSetSuccess() {
		return TravelServiceGetBudgetSummaryResult_Success_DEFAULT
	}
	return p.Success
}
func (p *TravelServiceGetBudgetSummaryResult) SetSuccess(x interface{}) {
	p.Success = x.(*model.Response)
}

func (p *TravelServiceGetBudgetSummaryResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *TravelServiceGetBudgetSummaryResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TravelServiceGetBudgetSummaryResult(%+v)", *p)
}

var fieldIDToName_TravelServiceGetBudgetSummaryResult = map[int16]string{
	0: "success",
}

type TravelServiceHealthArgs struct {
	Req *model.Request `thrift:"req,1" frugal:"1,default,model.Request" json:"req"`
}

func NewTravelServiceHealthArgs() *TravelServiceHealthArgs {
	return &TravelServiceHealthArgs{}
}

func (p *TravelServiceHealthArgs) InitDefault() {
}

var TravelServiceHealthArgs_Req_DEFAULT *model.Request

func (p *TravelServiceHealthArgs) GetReq() (v *model.Request) {
	if !p.IsSetReq() {
		return TravelServiceHealthArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *TravelServiceHealthArgs) SetReq(val *model.Request) {
	p.Req = val
}

func (p *TravelServiceHealthArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *TravelServiceHealthArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TravelServiceHealthArgs(%+v)", *p)
}

var fieldIDToName_TravelServiceHealthArgs = map[int16]string{
	1: "req",
}

type TravelServiceHealthResult struct {
	Success *model.Response `thrift:"success,0,optional" frugal:"0,optional,model.Response" json:"success,omitempty"`
}

func NewTravelServiceHealthResult() *TravelServiceHealthResult {
	return &TravelServiceHealthResult{}
}

func (p *TravelServiceHealthResult) InitDefault() {
}

var TravelServiceHealthResult_Success_DEFAULT *model.Response

func (p *TravelServiceHealthResult) GetSuccess() (v *model.Response) {
	if !p.IsSetSuccess() {
		return TravelServiceHealthResult_Success_DEFAULT
	}
	return p.Success
}
func (p *TravelServiceHealthResult) SetSuccess(x interface{}) {
	p.Success = x.(*model.Response)
}

func (p *TravelServiceHealthResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *TravelServiceHealthResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TravelServiceHealthResult(%+v)", *p)
}

var fieldIDToName_TravelServiceHealthResult = map[int16]string{
	0: "success",
}

type TravelServiceRequestRegistrationCodeArgs struct {
	Req *model.Request `thrift:"req,1" frugal:"1,default,model.Request" json:"req"`
}

func NewTravelServiceRequestRegistrationCodeArgs() *TravelServiceRequestRegistrationCodeArgs {
	return &TravelServiceRequestRegistrationCodeArgs{}
}

func (p *TravelServiceRequestRegistrationCodeArgs) InitDefault() {
}

var TravelServiceRequestRegistrationCodeArgs_Req_DEFAULT *model.Request

func (p *TravelServiceRequestRegistrationCodeArgs) GetReq() (v *model.Request) {
	if !p.IsSetReq() {
		return TravelServiceRequestRegistrationCodeArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *TravelServiceRequestRegistrationCodeArgs) SetReq(val *model.Request) {
	p.Req = val
}

func (p *TravelServiceRequestRegistrationCodeArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *TravelServiceRequestRegistrationCodeArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TravelServiceRequestRegistrationCodeArgs(%+v)", *p)
}

var fieldIDToName_TravelServiceRequestRegistrationCodeArgs = map[int16]string{
	1: "req",
}

type TravelServiceRequestRegistrationCodeResult struct {
	Success *model.Response `thrift:"success,0,optional" frugal:"0,optional,model.Response" json:"success,omitempty"`
}

func NewTravelServiceRequestRegistrationCodeResult() *TravelServiceRequestRegistrationCodeResult {
	return &TravelServiceRequestRegistrationCodeResult{}
}

func (p *TravelServiceRequestRegistrationCodeResult) InitDefault() {
}

var TravelServiceRequestRegistrationCodeResult_Success_DEFAULT *model.Response

func (p *TravelServiceRequestRegistrationCodeResult) GetSuccess() (v *model.Response) {
	if !p.IsSetSuccess() {
		return TravelServiceRequestRegistrationCodeResult_Success_DEFAULT
	}
	return p.Success
}
func (p *TravelServiceRequestRegistrationCodeResult) SetSuccess(x interface{}) {
	p.Success = x.(*model.Response)
}

func (p *TravelServiceRequestRegistrationCodeResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *TravelServiceRequestRegistrationCodeResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TravelServiceRequestRegistrationCodeResult(%+v)", *p)
}

var fieldIDToName_TravelServiceRequestRegistrationCodeResult = map[int16]string{
	0: "success",
}

type TravelServiceLegacyLoginArgs struct {
	Req *model.Request `thrift:"req,1" frugal:"1,default,model.Request" json:"req"`
}

func NewTravelServiceLegacyLoginArgs() *TravelServiceLegacyLoginArgs {
	return &TravelServiceLegacyLoginArgs{}
}

func (p *TravelServiceLegacyLoginArgs) InitDefault() {
}

var TravelServiceLegacyLoginArgs_Req_DEFAULT *model.Request

func (p *TravelServiceLegacyLoginArgs) GetReq() (v *model.Request) {
	if !p.IsSetReq() {
		return TravelServiceLegacyLoginArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *TravelServiceLegacyLoginArgs) SetReq(val *model.Request) {
	p.Req = val
}

func (p *TravelServiceLegacyLoginArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *TravelServiceLegacyLoginArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TravelServiceLegacyLoginArgs(%+v)", *p)
}

var fieldIDToName_TravelServiceLegacyLoginArgs = map[int16]string{
	1: "req",
}

type TravelServiceLegacyLoginResult struct {
	Success *model.Response `thrift:"success,0,optional" frugal:"0,optional,model.Response" json:"success,omitempty"`
}

func NewTravelServiceLegacyLoginResult() *TravelServiceLegacyLoginResult {
	return &TravelServiceLegacyLoginResult{}
}

func (p *TravelServiceLegacyLoginResult) InitDefault() {
}

var TravelServiceLegacyLoginResult_Success_DEFAULT *model.Response

func (p *TravelServiceLegacyLoginResult) GetSuccess() (v *model.Response) {
	if !p.IsSetSuccess() {
		return TravelServiceLegacyLoginResult_Success_DEFAULT
	}
	return p.Success
}
func (p *TravelServiceLegacyLoginResult) SetSuccess(x interface{}) {
	p.Success = x.(*model.Response)
}

func (p *TravelServiceLegacyLoginResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *TravelServiceLegacyLoginResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TravelServiceLegacyLoginResult(%+v)", *p)
}

var fieldIDToName_TravelServiceLegacyLoginResult = map[int16]string{
	0: "success",
}

type TravelServiceRequestEmailBindingCodeArgs struct {
	Req *model.Request `thrift:"req,1" frugal:"1,default,model.Request" json:"req"`
}

func NewTravelServiceRequestEmailBindingCodeArgs() *TravelServiceRequestEmailBindingCodeArgs {
	return &TravelServiceRequestEmailBindingCodeArgs{}
}

func (p *TravelServiceRequestEmailBindingCodeArgs) InitDefault() {
}

var TravelServiceRequestEmailBindingCodeArgs_Req_DEFAULT *model.Request

func (p *TravelServiceRequestEmailBindingCodeArgs) GetReq() (v *model.Request) {
	if !p.IsSetReq() {
		return TravelServiceRequestEmailBindingCodeArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *TravelServiceRequestEmailBindingCodeArgs) SetReq(val *model.Request) {
	p.Req = val
}

func (p *TravelServiceRequestEmailBindingCodeArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *TravelServiceRequestEmailBindingCodeArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TravelServiceRequestEmailBindingCodeArgs(%+v)", *p)
}

var fieldIDToName_TravelServiceRequestEmailBindingCodeArgs = map[int16]string{
	1: "req",
}

type TravelServiceRequestEmailBindingCodeResult struct {
	Success *model.Response `thrift:"success,0,optional" frugal:"0,optional,model.Response" json:"success,omitempty"`
}

func NewTravelServiceRequestEmailBindingCodeResult() *TravelServiceRequestEmailBindingCodeResult {
	return &TravelServiceRequestEmailBindingCodeResult{}
}

func (p *TravelServiceRequestEmailBindingCodeResult) InitDefault() {
}

var TravelServiceRequestEmailBindingCodeResult_Success_DEFAULT *model.Response

func (p *TravelServiceRequestEmailBindingCodeResult) GetSuccess() (v *model.Response) {
	if !p.IsSetSuccess() {
		return TravelServiceRequestEmailBindingCodeResult_Success_DEFAULT
	}
	return p.Success
}
func (p *TravelServiceRequestEmailBindingCodeResult) SetSuccess(x interface{}) {
	p.Success = x.(*model.Response)
}

func (p *TravelServiceRequestEmailBindingCodeResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *TravelServiceRequestEmailBindingCodeResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TravelServiceRequestEmailBindingCodeResult(%+v)", *p)
}

var fieldIDToName_TravelServiceRequestEmailBindingCodeResult = map[int16]string{
	0: "success",
}

type TravelServiceBindEmailArgs struct {
	Req *model.Request `thrift:"req,1" frugal:"1,default,model.Request" json:"req"`
}

func NewTravelServiceBindEmailArgs() *TravelServiceBindEmailArgs {
	return &TravelServiceBindEmailArgs{}
}

func (p *TravelServiceBindEmailArgs) InitDefault() {
}

var TravelServiceBindEmailArgs_Req_DEFAULT *model.Request

func (p *TravelServiceBindEmailArgs) GetReq() (v *model.Request) {
	if !p.IsSetReq() {
		return TravelServiceBindEmailArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *TravelServiceBindEmailArgs) SetReq(val *model.Request) {
	p.Req = val
}

func (p *TravelServiceBindEmailArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *TravelServiceBindEmailArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TravelServiceBindEmailArgs(%+v)", *p)
}

var fieldIDToName_TravelServiceBindEmailArgs = map[int16]string{
	1: "req",
}

type TravelServiceBindEmailResult struct {
	Success *model.Response `thrift:"success,0,optional" frugal:"0,optional,model.Response" json:"success,omitempty"`
}

func NewTravelServiceBindEmailResult() *TravelServiceBindEmailResult {
	return &TravelServiceBindEmailResult{}
}

func (p *TravelServiceBindEmailResult) InitDefault() {
}

var TravelServiceBindEmailResult_Success_DEFAULT *model.Response

func (p *TravelServiceBindEmailResult) GetSuccess() (v *model.Response) {
	if !p.IsSetSuccess() {
		return TravelServiceBindEmailResult_Success_DEFAULT
	}
	return p.Success
}
func (p *TravelServiceBindEmailResult) SetSuccess(x interface{}) {
	p.Success = x.(*model.Response)
}

func (p *TravelServiceBindEmailResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *TravelServiceBindEmailResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TravelServiceBindEmailResult(%+v)", *p)
}

var fieldIDToName_TravelServiceBindEmailResult = map[int16]string{
	0: "success",
}
